### ISSUE TITLE
Can't install cunn with luarocks because of missing file

### ISSUE THREAD

**Issue by joonazan** [torch/cunn#103]
[joonazan@arkkikaari char-rnn]$ luarocks install cunn
	Installing https://raw.githubusercontent.com/torch/rocks/master/cunn-scm-1.rockspec...
	Using https://raw.githubusercontent.com/torch/rocks/master/cunn-scm-1.rockspec... switching to 'build' mode
	Klone nach 'cunn' ...
	remote: Counting objects: 49, done.
	remote: Compressing objects: 100% (38/38), done.
	remote: Total 49 (delta 15), reused 21 (delta 7), pack-reused 0
	Empfange Objekte: 100% (49/49), 56.13 KiB | 0 bytes/s, Fertig.
	Löse Unterschiede auf: 100% (15/15), Fertig.
	Prüfe Konnektivität ... Fertig.
	cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/joonazan/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/joonazan/torch/install/lib/luarocks/rocks/cunn/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

	-- The C compiler identification is GNU 5.1.0
	-- The CXX compiler identification is GNU 5.1.0
	-- Check for working C compiler: /usr/bin/cc
	-- Check for working C compiler: /usr/bin/cc -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Detecting C compile features
	-- Detecting C compile features - done
	-- Check for working CXX compiler: /usr/bin/c++
	-- Check for working CXX compiler: /usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	-- Found Torch7 in /home/joonazan/torch/install
	-- Found CUDA: /opt/cuda (found suitable version "7.0", minimum required is "4.0") 
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /tmp/luarocks_cunn-scm-1-2819/cunn/build
	[100%] Building NVCC (Device) object CMakeFiles/cunn.dir/cunn_generated_init.cu.o
	In file included from /home/joonazan/torch/install/include/THC/THCApply.cuh:5:0,
	                 from /tmp/luarocks_cunn-scm-1-2819/cunn/HardTanh.cu:2,
	                 from /tmp/luarocks_cunn-scm-1-2819/cunn/init.cu:14:
	/home/joonazan/torch/install/include/THC/THCReduceApplyUtils.cuh:9:30: schwerwiegender Fehler: THCDeviceUtils.cuh: Datei oder Verzeichnis nicht gefunden
	Kompilierung beendet.
	CMake Error at cunn_generated_init.cu.o.cmake:206 (message):
	  Error generating
	  /tmp/luarocks_cunn-scm-1-2819/cunn/build/CMakeFiles/cunn.dir//./cunn_generated_init.cu.o

	CMakeFiles/cunn.dir/build.make:55: die Regel für Ziel „CMakeFiles/cunn.dir/cunn_generated_init.cu.o“ scheiterte
	make[2]: *** [CMakeFiles/cunn.dir/cunn_generated_init.cu.o] Fehler 1
	CMakeFiles/Makefile2:60: die Regel für Ziel „CMakeFiles/cunn.dir/all“ scheiterte
	make[1]: *** [CMakeFiles/cunn.dir/all] Fehler 2
	Makefile:116: die Regel für Ziel „all“ scheiterte
	make: *** [all] Fehler 2

	Error: Build error: Failed building.

**Comment by soumith** [comment]
Hi, this should be fixed now.

luarocks install cutorch
luarocks install cunn

There was a brief period of 2 hours this morning where trunk was broken.
