### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by YitzhakSp** [torch/cunn#113]
trying to install cunn I have the following problem (error at the bottom). any ideas how to fix it? :

root@yitzhak-VirtualBox:/media/sf_Dima/Projects_Torch/examples_from_github/eladhoffer/ConvNet-torch-master# luarocks install cunn
Installing https://raw.githubusercontent.com/torch/rocks/master/cunn-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cunn-scm-1.rockspec... switching to 'build' mode

Missing dependencies for cunn:
cutorch >= 1.0

Using https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec... switching to 'build' mode
Cloning into 'cutorch'...
remote: Counting objects: 75, done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 75 (delta 8), reused 22 (delta 1), pack-reused 0
Receiving objects: 100% (75/75), 106.22 KiB | 181.00 KiB/s, done.
Resolving deltas: 100% (8/8), done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/yitzhak/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/yitzhak/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/yitzhak/torch/install
CMake Error at /usr/share/cmake-2.8/Modules/FindCUDA.cmake:548 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:7 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cutorch-scm-1-1323/cutorch/build/CMakeFiles/CMakeOutput.log".

Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec - Build error: Failed building.

**Comment by soumith** [comment]
it couldn't find the CUDA toolkit on your machine. You might have to install it. 
https://github.com/facebook/fbcunn/blob/master/INSTALL.md#install-cuda

**Comment by eliksr** [comment]
on mac, trying to install cunn I have the following problem (error at the bottom). any ideas how to fix it? :

Installing https://raw.githubusercontent.com/torch/rocks/master/cunn-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cunn-scm-1.rockspec... switching to 'build' mode

Missing dependencies for cunn:
cutorch >= 1.0

Using https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec... switching to 'build' mode
Cloning into 'cutorch'...
remote: Counting objects: 203, done.
remote: Compressing objects: 100% (158/158), done.
remote: Total 203 (delta 57), reused 88 (delta 43), pack-reused 0
Receiving objects: 100% (203/203), 192.68 KiB | 130.00 KiB/s, done.
Resolving deltas: 100% (57/57), done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/Users/elik/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/Users/elik/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- The C compiler identification is AppleClang 8.0.0.8000038
-- The CXX compiler identification is AppleClang 8.0.0.8000038
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /Users/elik/torch/install
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found suitable version "7.5", minimum required is "6.5")
-- MAGMA not found. Compiling without MAGMA support
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;5.2+PTX
-- got cuda version 7.5
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
-- CUDA_NVCC_FLAGS: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_52,code=compute_52;-DCUDA_HAS_FP16=1
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_cutorch-scm-1-5758/cutorch/build
[  4%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o
[  3%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o
[  4%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o
[  5%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o
[  5%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
[  8%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o
[  8%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o
[  9%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o
nnvvcccc  nffvaacttcaa llf  a  t  a::l   TT hh ee:   vvTeehrress iivooennr  s((i'n8nov0vn'cn8c 0 (0f'0a80t0'a0)l0  0o ' cf0 )tv:chc e0 c  Tf0 hahtoeaf o lsv tt e  hc:roes mi Tpo'hh)nef ivo l saet(e 'rrc8so 0i(m0o'0npA i0pt(o'a'8l)lp ef0ol0rf0 e0 (' ')tcAh plop efl  e  ath htocnels gathn' g)oc os'hitms p :ie) cln  e ooirmt s ( 'pnsoAiutlppeppTrlo  ers (uc'plAptaopnrpetglede'd
)c
 liasn gn'o)t  issu pnpootr tseudp
phoerh tovesedtr
 scioomnp i(l'e8r0 0(0'0A'p)p loef  ctlhaen gh'o)s ti sc onmopti lseurp p(o'rAtpepdl
e clang') is not supported
nvcc fatal   : The version ('80000') of the host compiler ('Apple clang') is not supported
nvcc fatal   : The version ('80000') of the host compiler ('Apple clang') is not supported
CCMMaakkee  EErrrroorr  aatt  TTHHCC__ggeenneerraatteedd__TTHHCCCBTMleaanksse.o crEuMr.aroto.hrR. ecalute. aoTs.HeRC.e_clgmeeaankseeer:.a2ct0me7ad k_(eTm:He2C0sC7sS Ma(agtkemeoe r)Csa:sMEag
aekgre C eoE rE)orrrp:rr
 y oa. corErt  uga.etro n.rTeCorHRaCerMt_ iglneenga kTeaH CseeE_.rgcrermanoteaerdkr_ eT:aaCt2MtH0ea7 C TTkde(HnCmse_os_eTrHsg.C cETure.eanogr.enosRr)eer: olraeCaa
ttoe pd  _sTTEegn
He rHarCC rt_iognrR/ gteg
dmep un/c ee/ntleumrApaetapirpn/loglyc
r kU utsa/atriteoml_pcdcsk/.ulsu__actrcuoyToe.H.cCckmsHa_ackcuueul:t.2of0r.coth7.oc-Rrs cue(c.mmhle-esas-oCcs.1sMaR-g5e.a7)ko:5ee8
l.e mra-c1/Es ceuh-r-5.7srcc5mm8-ta/1okc-ereou :r5tcah7otr5 8c.T2/Hh/c/cb0Cmuubi7la_utgiol d(dk//emrl:l 2ieERr0icehbb//lT/eHbTuCH7r/ia Cs/(CClodrmM/ alMiegbska/ekTeeHFeCFsi/ilangeCleMe)sasee/k/:r
T.TeHHFaCicC t.msalkseia.en :dsdEi2gi/0
7rrr r// o/ /T/r.H.t/( T/CmmgHe.Tpen/nCe_rlagHetdCui_arergoinceke/nr/nsre.gar/_aTctgae
tH de_ uCT/d_ttH_gCmeToHnpSe/rCtlourraaTtcaeesdrgnts_eohTcCesHakod-p_ossyc._mccrTMu-Haute1)tC-o.h:5B.
lcoaus7
r.5 c
8oEh
/-r.
sc
crmu
co-tu1r.-oo r5g
cge7
)e5hn8/e/br
ucaiutltidon/rglc
ih b/ /b/TutHimCl/pdC//Mllauikaber/FoTicHlkCes/sC/_MTcaHukCte.oFdriilcreh/s-//s.Tc/HmTC-H.1Cd-_igr5e/7n/5e.8r//acTtCHueCtd_o_grTecHnhCe/Trebanustioelrdd._/cTSluHtiCob./ToTe
Hn
Cs/oCrMCao
kpeyF.iclue.rso/a
Tg
HeC..cdui.ro
//./THC_generated_THCHalf.cu.o

.R
elease.cmake:207 (message):
  Error generating
  /tmp/luarocks_cutorch-scm-1-5758/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o


:
  Error generating
  /tmp/luarocks_cutorch-scm-1-5758/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o


make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o] Error 1
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o] Error 1
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o] Error 1
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o] Error 1
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o] Error 1
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o] Error 1
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o] Error 1
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
make: *** [all] Error 2

Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec - Build error: Failed building.

**Comment by Yaffa1607** [comment]
Did you find a solution?

**Comment by eliksr** [comment]
yes, i searched for:
"nvcc fatal : The version ('80000') of the host compiler ('Apple clang') is not supported"

and found this solution: 
http://stackoverflow.com/questions/36250949/revert-apple-clang-version-for-nvcc

Then i had another issue with:
"error: implicit declaration of function 'THAtomicAddPtrdiff' is invalid in C99 [-Werror,-Wimplicit-function-declaration]"

So I ran update.sh script as someone said in:
https://github.com/torch/cutorch/issues/535

Finally it worked!

**Comment by mahesh-zarkar** [comment]
Error: Failed installing dependency.....I am getting the same error..I have install the cuda toolkit also...someone pls help me to solve the error

**Comment by shineYuSong** [comment]
use this to add a softlink  then it can work
$ sudo ln -s /usr/local/cuda-8.0 /usr/local/cuda
