### ISSUE TITLE
Padding is eaten away

### ISSUE THREAD

**Issue by Atcold** [torch/cunn#121]
I'm playing with `float` and `cuda` networks, and now I get this
```lua
th> model.modules[1].padding = 0
                                                                      [0.0001s]
th> model.modules[1].padding                                                                                                           
0
                                                                      [0.0001s]
th> model.modules[1]:forward(torch.CudaTensor(3,224,244))                                                                              
[string "_RESULT={model.modules[1]:forward(torch.CudaT..."]:1: bad argument #1 (field padding does not exist)
stack traceback:
        [C]: in function 'forward'
        [string "_RESULT={model.modules[1]:forward(torch.CudaT..."]:1: in main chunk
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/trepl/init.lua:630: in function 'repl'
        /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
        [C]: at 0x00406260
                                                                      [0.0008s]
th> model.modules[1].padding                                                                                                           
                                                                      [0.0000s]
th> 
```
How could I go over this?

**Comment by soumith** [comment]
padding is eaten away and replaced by .padW and .padH

**Comment by soumith** [comment]
https://github.com/torch/nn/commit/793b6bfef8f4fa51e7ddee9cfe34d0732de067a2

**Comment by Atcold** [comment]
OK, but I get the error. How can I forward the image successfully?

**Comment by soumith** [comment]
did you update cunn to the latest trunk? seems like you updated nn, but not cunn?

**Comment by soumith** [comment]
https://github.com/torch/cunn/blob/master/SpatialConvolutionMM.cu#L111

**Comment by Atcold** [comment]
Everything is just to the latest release.

**Comment by soumith** [comment]
i think that has to be double-checked. 

> bad argument #1 (field padding does not exist)

This error appears on the older version of cunn for sure, because of this line:
https://github.com/torch/cunn/blob/30e394d0c79a95d04df1d04f4dbef30d078ccb6a/SpatialConvolutionMM.cu#L124

but should not appear in trunk, because it is changed to:
https://github.com/torch/cunn/blob/master/SpatialConvolutionMM.cu#L111

**Comment by Atcold** [comment]
@soumith, my bad. `apt-get` broke `cuda` and `luarocks` didn't install `cunn`. My fault. Sorry...

**Comment by soumith** [comment]
no problem :)

**Comment by Atcold** [comment]
:+1:

**Comment by Atcold** [comment]
@soumith, one more note. With a broken `cuda`, `luarocks` installed only the `lua` files leaving out the `cu` one. That's why I had the `lua` killing my `padding` variable but the precompiled `cu` one asking for it. So, the semi-installed `cunn` gave me some weird troubles.
