### ISSUE TITLE
require 'cunn' throws error

### ISSUE THREAD

**Issue by lifeisnice90** [torch/cunn#142]
It seems to me that the file init.lua has changed recently and this change causes an error.
Line 9: "nn.Module._flattenTensorBuffer['torch.CudaTensor'] = torch.FloatTensor.new"
throws error if
"require 'cunn'"
is used.

In particular I get the following error (if I don't remove the line):
*******************
.../torch/install/share/lua/5.1/cunn/init.lua:9: attempt to index field '_flattenTensorBuffer' (a nil value)
stack traceback:
	.../torch/install/share/lua/5.1/cunn/init.lua:9: in main chunk
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: at 0x00406670

*******************

Thanks for your help!

**Comment by fmassa** [comment]
@lifeisnice90 did you tried updating `nn` ? `nn.Module._flattenTensorBuffer` was added in commit https://github.com/torch/nn/commit/7105419c8382c3a9c5c257661c8ab49872fdcddc , so it should work.

**Comment by lifeisnice90** [comment]
Thanks fmassa, that solved the problem!
