### ISSUE TITLE
[cmake] compile with the system card's compute capability

### ISSUE THREAD

**Issue by soumith** [torch/cunn#148]
cmake at compile-time should be able to determine the compute capability of the card. we should use this to set nvcc flags, rather than use sm20 by default.

Will fix https://github.com/torch/cunn/issues/144

**Comment by albanD** [comment]
Note: [this](https://github.com/BVLC/caffe/blob/6eae122a8eb84f8371dde815986cd7524fc4cbaa/cmake/Cuda.cmake#L9-L132) is the code in Caffe that is doing exactly what you're looking for I think.

**Comment by hughperkins** [comment]
Ah, nice find :-)  I tried dabbling with `nvidia-smi` options, and `nvcc` options, but nothing obvious popped out.

**Comment by albanD** [comment]
@soumith  I think this ca
