### ISSUE TITLE
SpatialFullConvolution test flaky

### ISSUE THREAD

**Issue by dominikgrewe** [torch/cunn#174]
The SpatialFullConvolution tests sometimes fail due to invalid configurations:

```
SpatialFullConvolution_forward_batch
 Function call failed 
.../cunn/test.lua:785: bad argument #1 to 'forward' (3D or 4D (batch mode) tensor is expected)
```

It can be reproduced when running
```sh
torch -lcunn -e "nn.testcuda({'SpatialFullConvolution_forward_batch','SpatialFullConvolution_backward_batch'}, false, 1, 1449228794)"
```

The input sizes don't make sense: `16,14, 0.33333333333333, 2.3333333333333`

I've only observed this in cunn, but I suspect the same could happen in nn.

**Comment by dominikgrewe** [comment]
@szagoruyko who wrote the test.

**Comment by soumith** [comment]
fixing it now.
