### ISSUE TITLE
Installation fails with `THCGenerateAllTypes.h No such file or directory`

### ISSUE THREAD

**Issue by yankov** [torch/cunn#180]
When running `luarocks install cunn`  build fails with `THCGenerateAllTypes.h No such file or directory`.
Copying the file manually helped: `cp ./extra/cutorch/lib/THC/THCGenerateAllTypes.h ~/torch/install/include/THC/`  
 
OS: Ubuntu 15.10
CC=gcc-4.9
CXX=g++-4.9

**Comment by soumith** [comment]
@yankov you need to update cutorch to latest as well.
luarocks install cutorch
luarocks install cunn

**Comment by yankov** [comment]
@soumith I did exactly that but it still failed. Only manual copy helped.

**Comment by soumith** [comment]
hmmm, sounds like a cmake bug then. Will fix now.

**Comment by soumith** [comment]
Fixed via https://github.com/torch/cutorch/commit/8635044661b332f65cb3a5947dc06380e40b3ad5

luarocks install cutorch
luarocks install cunn

should work now.

Thanks for reporting this Artem.
