### ISSUE TITLE
Implementing SoftShrink in GPU

### ISSUE THREAD

**Issue by edouardoyallon** [torch/cunn#191]
Hi,

Do you think it would be possible to implement SoftShrink for GPU? I'll try on my side, yet I was stated it is simple but I don't think I know enough of Torch and CUDA to do it correctly. 

Thanks a lot.

**Comment by fmassa** [comment]
I'm preparing a patch for it. Will send a PR in a few minutes

**Comment by soumith** [comment]
Fixed in latest trunk!
