### ISSUE TITLE
Volumetric crashes

### ISSUE THREAD

**Issue by cvondrick** [torch/cunn#197]
There might be a weird bug with VolumetricMaxPooling with cunn. Below is an isolated script to diagnose:

      require 'cutorch'
      require 'nn'
      require 'cunn'

      function new_seq()
        local places = nn.Sequential()
        places:add(nn.Linear(227,1))
        places:add(nn.Linear(1,4096))
        places:add(nn.View(4096, 1))
        return places
      end

      function video_features(nframes)

        local features = nn.Parallel(2, 3)
        features:add(new_seq())
        features:add(new_seq())

        local vid_feats = nn.Sequential()
        vid_feats:add(features)

        -- {{ spatial max pooling works... uncomment, and no craash
        --v id_feats:add(nn.View(4096, 2, 1))
        -- vid_feats:add(nn.SpatialMaxPooling(1,1, 1,1))
        -- end spatial }}

        -- {{ volumetric max pooling does not work...
        vid_feats:add(nn.View(4096, 2, 1, 1))
        vid_feats:add(nn.VolumetricMaxPooling(1,1, 1,1))
        -- end problematic line }}

        return vid_feats
      end

      batchsize = 128
      nframes = 2

      video = torch.zeros(batchsize, nframes, 227)

      model = video_features(nframes)

      video = video:cuda()
      model:cuda()

      print(model:forward(video):size())
      print(model:forward(video):size())
      print(model:forward(video):size())

On my machine, this script will correctly do one forward of the model. But the second forward will fail with:

    torch/distro/install/share/lua/5.1/nn/Parallel.lua:35: invalid configuration argument at torch/distro/extra/cutorch/lib/THC/generic/THCTensorCopy.cu:172
    stack traceback:
           [C]: in function 'copy'
        ...sense/torch/distro/install/share/lua/5.1/nn/Parallel.lua:35: in function 'updateOutput'
        ...nse/torch/distro/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        debug/help2.lua:48: in main chunk
        [C]: in function 'dofile'
        ...rch/distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

Some interesting notes:
- if you remove the :cuda() lines, then it works, suggesting this is part of cunn, not nn
- if you change the VolumetricMaxPooling to SpatialMaxPooling, then it doesn't crash
- if you reduce the batch size to be smaller, it doesn't crash

I am using the latest Torch7 release (re-installed yesterday), and GPU is a Titan X. The problem reproduces on several of our machines.

I am still new to Torch, so maybe it is my mistake. Thanks for the great community!

**Comment by kmul00** [comment]
@cvondrick Your exact code (copy pasted without any changes) works in my K20. Please update your `nn` and `cunn` package to see if the problem persists.

Here's the output that I get,

```lua
  128
 4096
    2
    1
    1
[torch.LongStorage of size 5]


  128
 4096
    2
    1
    1
[torch.LongStorage of size 5]


  128
 4096
    2
    1
    1
[torch.LongStorage of size 5]
```

**Comment by cvondrick** [comment]
Interesting! 

I've updated torch, nn, cunn, and cutorch (with $ luarocks install [package]), and tried on a couple of different machines (which have Titan X and K40), but still same effect. I also removed my torch directory, and downloaded everything again from the web.

**Comment by soumith** [comment]
Carl, what about your cuda or driver version

**Comment by cvondrick** [comment]
$ nvcc --version
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2015 NVIDIA Corporation
    Built on Thu_May__7_00:35:41_CDT_2015
    Cuda compilation tools, release 7.5, V7.5.6

Thanks for looking into it. I think this is the cuda and driver version. 

    $ nvidia-smi
    Wed Jan 20 00:47:02 2016
    +------------------------------------------------------+
    | NVIDIA-SMI 352.07     Driver Version: 352.07         |
    |-------------------------------+----------------------+----------------------+

This machine has Titan X

**Comment by soumith** [comment]
Ok I got a repro on my machine, looking into it.

**Comment by cvondrick** [comment]
thanks. Another person in our lab just reproduced on their install too.

**Comment by kmul00** [comment]
Why is that I cannot reproduce the error ?

I removed my existing installation of Torch, and made a fresh install. Even then it got executed correctly.

I have an older `nvidia driver` version

    NVIDIA-SMI 346.72     Driver Version: 346.72

Is that the reason ?

**Comment by soumith** [comment]
@cvondrick I wont get to fixing it till a couple of days (traveling), but I am guessing that it is to do with the 1x1x1 MaxPooling (why would one want to do 1x1x1?).

**Comment by soumith** [comment]
@kmul00 maybe you are lucky :)

**Comment by cvondrick** [comment]
Thanks @soumith!

Yes, you are right, it is related to the 1x1x1

This works:

    vid_feats:add(nn.View(128, 4, 4, 4)):add(nn.VolumetricMaxPooling(2,2,2, 1,1,1))
    vid_feats:add(nn.View(128, 4, 4, 4)):add(nn.VolumetricMaxPooling(4,4,4, 1,1,1))

but these do not:

    vid_feats:add(nn.View(512, 2, 2, 2)):add(nn.VolumetricMaxPooling(2,2,2, 1,1,1))
    vid_feats:add(nn.View(512, 2, 2, 2)):add(nn.VolumetricMaxPooling(1,1,1, 1,1,1))

I guess there is just an edge case here.

As for why 1x1x1, just was debugging model and wanted to make everything very simple. clearly, I got the opposite of simple :) 

thanks!

**Comment by cvondrick** [comment]
We got hit by this bug again. I think there is an edge case when you don't want to pool in one dimension. Anyways, a work around is to convert to cudnn, which seems to not have this bug.


```
require 'nn'
require 'cunn'
require 'cudnn'

local fb1 = nn.Sequential()
fb1:add(nn.VolumetricConvolution(3,192,3,11,11,1,4,4,1,2,2))
fb1:add(nn.VolumetricMaxPooling(1,3,3,1,2,2))
fb1:add(nn.VolumetricConvolution(192,384,3,4,4,1,1,1,1,1,1))

data = torch.zeros(30, 3, 18, 227, 227)

fb1:cuda()
data = data:cuda()

-- uncomment next line to work around bug
-- fb1 = cudnn.convert(fb1, cudnn)

print{fb1:forward(data)}
```
