### ISSUE TITLE
Forwarding inf through nn.Max causes segfault `an illegal memory access was encountered at /home/ubuntu/git/cutorch/lib/THC/generic/THCStorage.c` on backprop

### ISSUE THREAD

**Issue by hughperkins** [torch/cunn#210]
Forwarding `inf` through nn.Max causes segfault `an illegal memory access was encountered at /home/ubuntu/git/cutorch/lib/THC/generic/THCStorage.c` on backprop

Test code:
```
require 'cutorch'

a = torch.CudaTensor(10, 10):fill(-1/0)
m, i = a:max(1)
print('i[1][1]', i[1][1])

require 'cunn'

net = nn.Max(1)
net:cuda()

for it=1,3 do
  out = net:forward(a)
  net:backward(a, torch.CudaTensor(10):uniform())
end
```

Result:
```
i[1][1] -1
luajit: cuda runtime error (77) : an illegal memory access was encountered at /h
ome/ubuntu/git/cutorch/lib/THC/generic/THCStorage.c:147
```

This is really hard to diagnose and debug, because the error becomes apparent significantly later in the program.

The immediate root cause is in cutorch, which has a default of `-1` for indices, on Max, which then when fed back into scatter, cause the cuda exception.  In THCTensorMathTransformReduce.cu, changing:
```
  thrust::pair<float,float> init = thrust::make_pair<float,float>(maxfloat32, -1);
```
To:
```
  thrust::pair<float,float> init = thrust::make_pair<float,float>(maxfloat32, 1);
```
... will fix the problem.

**Comment by soumith** [comment]
Fixed now after merging #332
