### ISSUE TITLE
cunn installation got stuck after found cuda

### ISSUE THREAD

**Issue by kepricon** [torch/cunn#220]
Hi all 

I've used Torch as my first frame work when i make DL application.

Recently, we bought new machine and started to install Torch on that machine.
After installing torch, when i tried to install cunn via luarocks, i got stuck.

The below is my result of "luarocks install cunn". (after list lined printed, there is no progress for tens of hours)

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/bda-master/kepricon/Project/torch/install
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-7.5 (found suitable version "7.5", minimum required is "5.5") 

and the below is  process info(grep luarocks)

bda-master@bdalab12:~/kepricon/git$ ps -ef | grep luarocks
bda-mas+ 104249  99487  0 08:14 pts/1    00:00:00 /home/bda-master/kepricon/Project/torch/install/bin/luajit /home/bda-master/kepricon/Project/torch/install/bin/luarocks install cunn --verbose
bda-mas+ 104336 104249  0 08:14 pts/1    00:00:00 sh -c cd '/tmp/luarocks_cutorch-scm-1-2257/cutorch' && cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/bda-master/kepricon/Project/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/bda-master/kepricon/Project/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install 
bda-mas+ 104338 104336  2 08:14 pts/1    00:00:00 cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/home/bda-master/kepricon/Project/torch/install/bin/.. -DCMAKE_INSTALL_PREFIX=/home/bda-master/kepricon/Project/torch/install/lib/luarocks/rocks/cutorch/scm-1
bda-mas+ 104538 104338  0 08:14 pts/1    00:00:00 /usr/local/cuda-7.5/bin/nvcc --run /tmp/luarocks_cutorch-scm-1-2257/cutorch/build/detect_cuda_archs.cu
bda-mas+ 104595 104144  0 08:15 pts/7    00:00:00 grep luarocks

Do you guys have any idea?

DH

**Comment by albanD** [comment]
Does the cuda samples work properly?

**Comment by kepricon** [comment]
Thank you.
The problem was some zombie process that made cuda not working.
after i restarted machine, it works.

Thank you
