### ISSUE TITLE
Linear layer weights mismatch in CUDA

### ISSUE THREAD

**Issue by dasguptar** [torch/cunn#226]
There seems to be some issue with weights of the `Linear` layer on the GPU.
```
require 'cunn';
model = nn.Linear(25088,4096)
model.weight:fill(1);
-- CUDA
model:cuda()
print(model.weight:numel())
print(model.weight:sum())
-- CPU
model:double()
print(model.weight:numel())
print(model.weight:sum())
```

The above snippet produces the following output:
```
-- CUDA
102760448
102760464 -- ???
-- CPU
102760448
102760448
```

I'm seeing this happen for any `Linear` layer with more than `8912x4096` weights.
What seems to be the issue here?

**Comment by soumith** [comment]
@dasguptar it's just the sum that's the issue, not the weights. you are crossing float precision limits.

**Comment by dasguptar** [comment]
@soumith, yeah, I suspected that was the issue. So any workaround for this? Other than converting a module to `float` or `double` from `cuda` every time I need to do something like this?
Also, why is crossing the precision limit giving me an answer that is greater than the actual answer? :worried:
