### ISSUE TITLE
Does Sharing of parameters work across two GPU's?

### ISSUE THREAD

**Issue by mansirankawat** [torch/cunn#231]
I am trying to use modules that share the parameters across two GPU's using DataParallelTable. Will the sharing of parameters work across GPU's?

**Comment by soumith** [comment]
If you have shared parameters in your network, they will continue to be shared, DataParallelTable parallelizes over the data, not the parameters.

Next time, could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking. We'll happily reply there. Thanks.

**Comment by mansirankawat** [comment]
Sure thanks!
