### ISSUE TITLE
Very slow SpatialConvolutionLocal

### ISSUE THREAD

**Issue by cpra** [torch/cunn#232]
The CUDA version of `SpatialConvolutionLocal` is very slow on my system.

```
local nn = require('nn')
local cunn = require('cunn')

torch.setdefaulttensortype('torch.FloatTensor')

local inputs = torch.Tensor(64, 1, 64, 64)
local timer = torch.Timer()
local rep = 10

local function bench(layer, inputs)
    print(layer)
    timer:reset()
    for r = 1,rep do local outputs = layer:forward(inputs) end
    print(string.format(' sec/rep: %g', timer:time().real / rep))
end

print('CPU versions:')

bench(nn.SpatialConvolution(1, 16, 3,3, 1,1, 1,1), inputs)
bench(nn.SpatialConvolutionLocal(1, 16, 64,64, 3,3, 1,1, 1,1), inputs)

print('CUDA versions:')

bench(nn.SpatialConvolution(1, 16, 3,3, 1,1, 1,1):cuda(), inputs:cuda())
bench(nn.SpatialConvolutionLocal(1, 16, 64,64, 3,3, 1,1, 1,1):cuda(), inputs:cuda())
```

Output:

```
CPU versions:   
nn.SpatialConvolution(1 -> 16, 3x3, 1,1, 1,1)
 sec/rep: 0.00671198    
nn.SpatialConvolutionLocal(1 -> 16, 64x64, 3x3, 1,1, 1,1)
 sec/rep: 0.102975
CUDA versions:  
nn.SpatialConvolution(1 -> 16, 3x3, 1,1, 1,1)
 sec/rep: 0.006271  
nn.SpatialConvolutionLocal(1 -> 16, 64x64, 3x3, 1,1, 1,1)
 sec/rep: 13.609
```

Torch, nn, cunn, and all other related packages are up to date. ArchLinux x64, Latest drivers and CUDA (361.28-2 and 7.5.18-1). Titan Black GPU.

**Comment by ibmua** [comment]
Ran it while running another neural network in the background in a Titan X. Well, SpatialConv got  sec/rep: 0.00200651, the Local didn't even finish in like 10 minutes, so I turned Jupyter off. Seems like somebody made quite a bug.

**Comment by cxy7452** [comment]
hmm, i'm also getting extremely slow spatialconvolutionlocal (bug?), and this doesn't have a cudnn binding. @soumith is this maybe on your list somewhere?

**Comment by fmassa** [comment]
@cxy7452 I'm not sure there is a `SpatialConvolutionLocal` function in `cudnn` library, so need to what for NVidia to implement it before writing a binding.

There is a way of making things faster on `SpatialConvolutionLocal`.
Just replace [this double loop](https://github.com/torch/cunn/blob/master/lib/THCUNN/generic/SpatialConvolutionLocal.cu#L152-L160) with a call to batch addmm ([which was recently updated to be non-blocking and thus faster](https://github.com/torch/cutorch/pull/601)).
You could try applying the [opposite patch of this commit](https://github.com/torch/cunn/pull/183/commits/97d8aab8271c21df35457d979d8ecd34214039e3) to see if things go faster on your side.

**Comment by cxy7452** [comment]
Hi @fmassa ,

Thank you for the response! I'm not very sure how to apply your suggested solution...would you maybe provide a step-by-step so I can try the steps out? Much apprecicated....!

**Comment by cxy7452** [comment]
do you mean to just uncomment the line

`THCudaTensor_baddbmm(state, output3d, 1.0, output3d, 1.0, weight, finput3d);`

and comment out the double for-look, that was swapped in with a double for loop back in Jan this year?

**Comment by fmassa** [comment]
@cxy7452 yes. But you will need to change the function name, as new types were introduced to cutorch. Something like

`THCTensor_(baddbmm)` instead of `THCudaTensor_baddbmm`

**Comment by cxy7452** [comment]
hi @fmassa 

I think I understand what you mean, I'd also need to update my cutorch for the updated baddbmm right? Also, I see that there are 3 occurrences of those baddbmm that got swapped out by the double for loops, so do I make the change to all 3 of them?

Also....sorry for a noob question but I've been just installing and updating torch packages using luarocks install cunn, if I just clone the latest cunn from github and make those changes, how do I get it to work with my current torch on my local system? Thanks...!

**Comment by fmassa** [comment]
Yes, you will need the updated cutorch.
It would be better to change it in all 3 places, but you'd need to first benchmark the changes to see if indeed you gain something speedwise.

to compile locally, do something like the following in the cloned repo

`luarocks make rocks/*`

**Comment by cxy7452** [comment]
@fmassa it works! Haven't tried backward pass yet, but the forward pass is now much faster than before, for my network CPU version's forward pass takes 3.2 sec, and the updated cunn version of SpatialConvolutionLocal takes about 1.9 sec for the forward pass. I guess this is probably the fastest a SpatialConvolutionLocal can get at this point, and the only way to make it faster is if Nvidia has it for cudnn? Or do you have any other ideas of making this faster?

how about cuda-convnet2? it also has SpatialConvolutionLocal and I wonder if that runs faster than the cunn version of it?

**Comment by fmassa** [comment]
I don't know about cuda-convnet2, might be faster but you'd need to check. I think that cuda-convnet2 has some restrictions on kernel size/image size though.
if you could run the cunn tests to make sure that it works as before, and then compare the timings vefore/after and apply the patch for the backward, could you please send a PR to cunn?

**Comment by cxy7452** [comment]
Sure I will check those and then send a pull request to cunn.

by the way I just tried cuda-convnet2's SpatialConvolutionLocal, like you said it does have restrictions on kernel size and image size:

image has to be square
input has to have a batch in the multiples of 32
convolution kernel's input plane has to be 1,2,3,4 or multiples of 4
convolution kernel's output plane has to be multiples of 16

after satisfying those restrictions, my cuda-convnet2's network is slightly larger (10% more local convolution kernels than the cunn version), but a forward pass using cuda-convnet2 only took 0.037 sec instead of 3.2 sec using cunn, so perhaps for now if people want to use SpatialConvolutionLocal, use the cuda-convnet2's version would be the fastest way. Will check more to make sure, but it seems like ccn2 is the way to go for now.

Again THANK YOU @fmassa!

**Comment by cxy7452** [comment]
hmm, didn't pass any of the tests, got an error for unimplemented data type:

/torch/install/share/lua/5.1/nn/THNN.lua:110: unimplemented data type at /tmp/luarocks_cutorch-scm-1-7346/cutorch/lib/THC/generic/THCTensorMathBlas.cu:596

I pretty much just commented out the double for loop, and updated the original baddbmm statement with:

`THCTensor_(baddbmm)(state, output3d, ScalarConvert<int, real>::to(1), output3d, ScalarConvert<int, real>::to(1), weight, finput3d);`

this is the first occurrence of the three. Maybe I did something wrong here?

**Comment by soumith** [comment]
@cxy7452 i'm working on fixing this.

**Comment by cxy7452** [comment]
thank you guys so much @soumith and @fmassa  !!!

**Comment by ibmua** [comment]
It's not as bad as it was before now, but it still is pretty darn awful, unfortunately, still worse than it even is on CPU.

**Comment by soumith** [comment]
hey @ibmua . at this point SpatialConvolutionLocal is a very niche module. The CPU side is open for improvement, but I dont think i will put any effort. Pull Requests welcome.

**Comment by ibmua** [comment]
Ok, anyway, thanks for that fix. =)
