### ISSUE TITLE
Numerical errors in SpatialSubSampling_backward test

### ISSUE THREAD

**Issue by apaszke** [torch/cunn#236]
When I use a seed of 1457471892, SpatialSubSampling_backward tests fails due to a very high numerical error in `test.lua:1476` (`LT failed: 0.67516082525253 >= 0.01`).

**Comment by fmassa** [comment]
This is falling for a long time. I think until now nobody cared about checking the source of the error.

**Comment by soumith** [comment]
same with upsampling. weirdly, they only fail on some systems and not on others.

**Comment by apaszke** [comment]
Uh, true. I now realised that it's a duplicate of #117, but at least it provides a seed. I guess we should close this one, right?

**Comment by soumith** [comment]
David Saxton fixed this.
