### ISSUE TITLE
nn.DataParallelTable error when using nn.gModule with multiple GPUs

### ISSUE THREAD

**Issue by namhoonlee** [torch/cunn#241]
Hi,

Recently I had to change my model and started using graph. It's fine when I use only single GPU, but the following error happens when I create nn.DataParallelTable to use Multiple GPUs.
"FATAL THREAD PANIC: (read) /home/mypath/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <nn.gModule>" 

The error happens when I add the model (which is nn.gModule) to nn.DataParallelTable. 

Please note that the followings are fine.
1) a network without graph using multiple GPUs
2) a network without graph using single GPU
3) a network with graph using single GPU

Can anyone experience similar issues? Any advice will be greatly appreciated.
Thanks!

**Comment by soumith** [comment]
@namhoonlee can you give a small code snippet to give the error? In around 50 lines of code or less, a dummy example should do fine.

**Comment by namhoonlee** [comment]
While translating into a small code, I found out that the last line gives me an error!

```
model = require('models/' .. opt.netType)(opt)
criterion = nn.MSECriterion:cuda()

gpus = torch.range(1, opt.nGPU):totable() 
dpt = nn.DataParallelTable(1, true, true)
        :add(model,gpus)
	:threads(function()
		local cudnn = require 'cudnn'
		cudnn.fastest, cudnn.benchmark = true, true
		end)
dpt.gradInput = nil
model = dpt:cuda()

parameters, gradParameters = model:getParameters()
```

This error also happens when I turn off the flags to DataParallelTable.

**Comment by colesbury** [comment]
If you are using nngrpah, tou probably need to `require 'nngraph'` inside the `:threads(function() ... end)`

**Comment by namhoonlee** [comment]
Wow that really solved out the issue..!
Thanks a lot for taking care of this issue @colesbury! 
You saved my day~

**Comment by yunhunJang** [comment]
I have similar problem.
I'm using rnn package (https://github.com/Element-Research/rnn) and ConvLSTM (https://github.com/viorik/ConvLSTM) for my model.

Running with multi gpu gave me thread panic error as well, so I include ```require 'rnn'``` and ```require <path_to_ConvLSTM_directory>``` right after ```local cudnn = require 'cudnn'```.

However, it gives me the error ```no field preload.package(<ConvLSTM_path>)```, while I'm using same require statement with same path in model definition script, and it works perfectly in case of single GPU.

Does anyone have the solution? Thanks!

**Comment by yunhunJang** [comment]
Okay, I fixed the problem.

Previously, <path_to_ConvLSTM_directory> includes ```..``` to describes its location.
After I moved it to my working directory and ```./ConvLSTM/ConvLSTM``` it works nicely.

**Comment by wandering007** [comment]
Same issue when processing `model:parameters()`:
```
FATAL THREAD PANIC: (read) /home/changmao/torch/install/share/lua/5.2/torch/File.lua:343: unknown Torch class <nn.Reorg>
FATAL THREAD PANIC: (read) /home/changmao/torch/install/share/lua/5.2/torch/File.lua:343: unknown Torch class <nn.Reorg>
```

`<nn.Reorg>` is a custom layer defined in `models/Reorg.lua`. It works fine in the CPU and single GPU cases.
