### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_52'

### ISSUE THREAD

**Issue by pby5** [torch/cunn#242]
when install cunn on ubuntu, meet an error "nvcc fatal   : Unsupported gpu architecture 'compute_52'
", how to slove it ? thx

**Comment by albanD** [comment]
Upgrading your CUDA installation will solve the problem.

**Comment by pby5** [comment]
we use TiTanX and cuda 7.5, and why occur this error?

**Comment by albanD** [comment]
You have multiple cuda installations on your system. You should properly remove the old version before installing torch.
