### ISSUE TITLE
accGradParameters() for SparseLinear, the cusparse call

### ISSUE THREAD

**Issue by pengsun** [torch/cunn#256]
Hi,

Actually it's a question rather than reporting an issue :-) 

The accGradParameters() code for SparseLinear is actually a multiplication between the transpose of a sparse matrix (input) and a dense matrix (gradOutput) by a call to cusparse library, where two possible implementations arise:

1) Call with the CUSPARSE_OPERATION_TRANSPOSE flag
2) Secretly/Implicitly transpose the sparse matrix (by extra code generating the values in column-major layout and the column ptr) and call with CUSPARSE_OPERATION_NON_TRANSPOSE flag

The current code (https://github.com/torch/cunn/blob/master/lib/THCUNN/SparseLinear.cu#L186-L196) seems to adopt the second impl. Just out of curiosity, wondering if there is any memory/speed consideration for choosing this? As I understand, the first impl can reuse the cusparse matrix representation (values, rowPtr, colInd) from the updataOutput() call and therefore should be faster. Any comment on this?

**Comment by soumith** [comment]
cc: @ebetica

**Comment by ebetica** [comment]
I noticed that for a large problems, technique 2 seemed faster. I think this is due to the memory access patterns of having values close by when doing the expensive matrix multiplication. Feel free to do more rigorous experimentation to see how true that is.
