### ISSUE TITLE
Getting identifier "__shfl_down" is undefined error on Ubuntu 14.04 when installing cunn

### ISSUE THREAD

**Issue by eyezis** [torch/cunn#264]
I have previously (late 2015) installed cunn successfully on this machine. This a fresh install of Ubuntu 14.04 with Cuda 7.0 

	Installing https://raw.githubusercontent.com/torch/rocks/master/cunn-scm-1.rockspec...
	Using https://raw.githubusercontent.com/torch/rocks/master/cunn-scm-1.rockspec... switching to 'build' mode
	Cloning into 'cunn'...
	remote: Counting objects: 76, done.
	remote: Compressing objects: 100% (70/70), done.
	remote: Total 76 (delta 20), reused 20 (delta 2), pack-reused 0
	Receiving objects: 100% (76/76), 94.44 KiB | 0 bytes/s, done.
	Resolving deltas: 100% (20/20), done.
	Checking connectivity... done.
	cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/dank/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/dank/torch/install/lib/luarocks/rocks/cunn/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

	-- The C compiler identification is GNU 4.8.4
	-- The CXX compiler identification is GNU 4.8.4
	-- Check for working C compiler: /usr/bin/cc
	-- Check for working C compiler: /usr/bin/cc -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Check for working CXX compiler: /usr/bin/c++
	-- Check for working CXX compiler: /usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Found Torch7 in /home/dank/torch/install
	-- Found CUDA: /usr/local/cuda (found suitable version "7.0", minimum required is "6.5") 
	-- Compiling for CUDA architecture: 2.1(2.0)
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /tmp/luarocks_cunn-scm-1-4200/cunn/build
	[  4%] [  4%] [  6%] [  8%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialReplicationPadding.cu.o
	Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_MarginCriterion.cu.o
	Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_MultiMarginCriterion.cu.o
	Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialCrossMapLRN.cu.o
	^Cnvcc error   : '"/usr/bin"/cc' died due to signal 2 
	nvcc error   : '"/usr/bin"/cc' died due to signal 2 
	nvcc error   : '"/usr/bin"/cc' died due to signal 2 
	nvcc error   : '"/usr/bin"/cc' died due to signal 2 
	make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_MultiMarginCriterion.cu.o] Interrupt
	make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_SpatialCrossMapLRN.cu.o] Interrupt
	make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_SpatialReplicationPadding.cu.o] Interrupt
	make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_MarginCriterion.cu.o] Interrupt
	make[1]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/all] Interrupt
	make: *** [all] Interrupt

	Error: Build error: Failed building.
	dank@linuxisbetter:~$ luarocks install FindCUDA
	Installing https://raw.githubusercontent.com/torch/rocks/master/findcuda-scm-1.rockspec...
	Using https://raw.githubusercontent.com/torch/rocks/master/findcuda-scm-1.rockspec... switching to 'build' mode
	Cloning into 'FindCUDA'...
	remote: Counting objects: 13, done.
	remote: Compressing objects: 100% (12/12), done.
	remote: Total 13 (delta 1), reused 11 (delta 1), pack-reused 0
	Receiving objects: 100% (13/13), 32.94 KiB | 0 bytes/s, done.
	Resolving deltas: 100% (1/1), done.
	Checking connectivity... done.
	cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/dank/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/dank/torch/install/lib/luarocks/rocks/findcuda/scm-1" && make install

	-- The C compiler identification is GNU 4.8.4
	-- The CXX compiler identification is GNU 4.8.4
	-- Check for working C compiler: /usr/bin/cc
	-- Check for working C compiler: /usr/bin/cc -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Check for working CXX compiler: /usr/bin/c++
	-- Check for working CXX compiler: /usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Found Torch7 in /home/dank/torch/install
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /tmp/luarocks_findcuda-scm-1-2402/FindCUDA/build
	Install the project...
	-- Install configuration: "Release"
	-- Installing: /home/dank/torch/install/share/cmake/torch/FindCUDA.cmake
	-- Installing: /home/dank/torch/install/share/cmake/torch/FindCUDA/make2cmake.cmake
	-- Installing: /home/dank/torch/install/share/cmake/torch/FindCUDA/parse_cubin.cmake
	-- Installing: /home/dank/torch/install/share/cmake/torch/FindCUDA/run_nvcc.cmake
	cd build
	Updating manifest for /home/dank/torch/install/lib/luarocks/rocks
	findcuda scm-1 is now built and installed in /home/dank/torch/install/ (license: MIT)

	dank@linuxisbetter:~$ luarocks install cunn
	Installing https://raw.githubusercontent.com/torch/rocks/master/cunn-scm-1.rockspec...
	Using https://raw.githubusercontent.com/torch/rocks/master/cunn-scm-1.rockspec... switching to 'build' mode
	Cloning into 'cunn'...
	remote: Counting objects: 76, done.
	remote: Compressing objects: 100% (70/70), done.
	remote: Total 76 (delta 20), reused 20 (delta 2), pack-reused 0
	Receiving objects: 100% (76/76), 94.44 KiB | 0 bytes/s, done.
	Resolving deltas: 100% (20/20), done.
	Checking connectivity... done.
	cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/dank/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/dank/torch/install/lib/luarocks/rocks/cunn/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

	-- The C compiler identification is GNU 4.8.4
	-- The CXX compiler identification is GNU 4.8.4
	-- Check for working C compiler: /usr/bin/cc
	-- Check for working C compiler: /usr/bin/cc -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Check for working CXX compiler: /usr/bin/c++
	-- Check for working CXX compiler: /usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Found Torch7 in /home/dank/torch/install
	-- Looking for include file pthread.h
	-- Looking for include file pthread.h - found
	-- Looking for pthread_create
	-- Looking for pthread_create - not found
	-- Looking for pthread_create in pthreads
	-- Looking for pthread_create in pthreads - not found
	-- Looking for pthread_create in pthread
	-- Looking for pthread_create in pthread - found
	-- Found Threads: TRUE  
	-- Found CUDA: /usr/local/cuda (found suitable version "7.0", minimum required is "6.5") 
	-- Compiling for CUDA architecture: 2.1(2.0)
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /tmp/luarocks_cunn-scm-1-5496/cunn/build
	[  6%] [  6%] [  6%] [  8%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_MarginCriterion.cu.o
	Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialReplicationPadding.cu.o
	Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_MultiMarginCriterion.cu.o
	Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialCrossMapLRN.cu.o
	[ 10%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialAveragePooling.cu.o
	[ 12%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SoftPlus.cu.o
	[ 14%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialClassNLLCriterion.cu.o
	/tmp/luarocks_cunn-scm-1-5496/cunn/lib/THCUNN/SpatialClassNLLCriterion.cu(16): error: identifier "__shfl_down" is undefined

	1 error detected in the compilation of "/tmp/tmpxft_00002846_00000000-7_SpatialClassNLLCriterion.cpp1.ii".
	CMake Error at THCUNN_generated_SpatialClassNLLCriterion.cu.o.cmake:266 (message):
	  Error generating file
	  /tmp/luarocks_cunn-scm-1-5496/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialClassNLLCriterion.cu.o

	make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_SpatialClassNLLCriterion.cu.o] Error 1
	make[2]: *** Waiting for unfinished jobs....
	make[1]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/all] Error 2
	make: *** [all] Error 2

	Error: Build error: Failed building.

**Comment by apaszke** [comment]
Sorry, I forgot that __shfl_* intrinsics are only available for architectures >= Kepler :confused:
Unfortunately I will be at my computer no sooner than tomorrow evening and only then can I fix it.
@soumith If you can do it sooner, it can be fixed by using 2 blockReduce calls in updateOutput

**Comment by soumith** [comment]
should be fixed in trunk now, i reverted it for now.
