### ISSUE TITLE
Restrict register usage of LRNFillScale TK1

### ISSUE THREAD

**Issue by verdimrc** [torch/cunn#271]
Running [cmusatyalab/openface](https://github.com/cmusatyalab/openface) on TK1 requires changing  line 5 in `lib/THCUNNSpatialCrossMapLRN.cu` from
```cuda
__global__ void LRNFillScale(const int nthreads, const Dtype* const in,
```
to
```cuda
__global__ void __launch_bounds__(CUDA_NUM_THREADS) LRNFillScale(const int nthreads, const Dtype* const in,
```

The `__launch_bounds__` qualifier limits the kernel to use 32,768 registers/block (i.e., 32 registers/thread, 1024 threads/block). Without it, openface throws this error:
```
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-5749/cutorch/lib/THC/THCGeneral.c line=608 error=7 : too many resources requested for launch
/usr/local/share/lua/5.1/nn/Container.lua:67:
In 6 module of nn.Sequential:
/usr/local/share/lua/5.1/nn/THNN.lua:109: cuda runtime error (7) : too many resources requested for launch at /tmp/luarocks_cutorch-scm-1-5749/cutorch/lib/THC/THCGeneral.c:608
stack traceback:
        [C]: in function 'v'
        /usr/local/share/lua/5.1/nn/THNN.lua:109: in function 'SpatialConvolutionMM_updateOutput'
        /usr/local/share/lua/5.1/nn/SpatialConvolutionMM.lua:79: in function </usr/local/share/lua/5.1/nn/SpatialConvolutionMM.lua:69>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /usr/local/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        [string "_RESULT={net:forward(input)}"]:1: in main chunk
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/trepl/init.lua:651: in function 'repl'
        /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
        [C]: at 0x0000d055

[The rest of error message is omitted]
```

Even though the exception is thrown at the `SpatialConvolutionMM` layer, the source of the error is actually at its preceding layer which is the `SpatialCrossMapLRN` layer.

By further using `nvprof` to compare the execution profile to `cunn` compiled with `-maxrregcount 32`, it is determined that the the error occurs when launching `LRNFillScale`.

**Comment by szagoruyko** [comment]
you can send a PR, keep in mind that you need to hide it behind CUDA_ARCH version check macro https://github.com/torch/cutorch/blob/cd2fbbbe3b0e537858605c4c6eb6cba16a65aa50/lib/THC/THCApply.cuh#L43

**Comment by verdimrc** [comment]
Thanks. PR submitted & merged.
