### ISSUE TITLE
Converting to CudaTensor in worker thread incompatible with DataParallelTable?

### ISSUE THREAD

**Issue by RuiShu** [torch/cunn#275]
I've been creating my minibatches using a threadpool in a manner similar to https://github.com/soumith/dcgan.torch/blob/master/data/data.lua. I also happen to perform the minibatch CudaTensor conversion in the worker thread prior to passing the tensor back to the main thread. This works fine by itself.

However, when I use the above approach when training a model that uses DataParallelTable, the program will abruptly stall (perhaps because of a blocking call in DataParallelTable?). This behavior only occurs if I perform the CudaTensor conversion in the worker thread, and does not occur if I perform the conversion in the main thread. 

Is this expected behavior? 

Thanks!

**Comment by soumith** [comment]
This is expected behavior because you are using the default stream (even though it's in a separate thread). Unless you know how to use cutorch's streams API, and know what you are doing with CUDA, dont do this and do all cuda calls in main thread.
