### ISSUE TITLE
Installation problem with luarocks

### ISSUE THREAD

**Issue by Henderake** [torch/cunn#295]
I cannot install cunn with `luarocks install cunn`. I have installed cutorch but `luarocks install cunn` gives me the following error message:

> cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/user/usr/local/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/user/usr/local/torch/install/lib/luarocks/rocks/cunn/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install
> 
> -- The C compiler identification is GNU 4.9.2
> -- The CXX compiler identification is GNU 4.9.2
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Found Torch7 in /home/user/usr/local/torch/install
> -- Found CUDA: /usr/local/cuda (found suitable version "7.5", minimum required is "6.5")
> -- Compiling for CUDA architecture: 5.2 5.2
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /tmp/luarocks_cunn-scm-1-4635/cunn/build
> [  8%] [  8%] [  8%] [  8%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_Square.cu.o
> Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SoftPlus.cu.o
> Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_BatchNormalization.cu.o
> Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_ELU.cu.o
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THStorage.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THStorageCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THStorage.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCStorage.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THStorageCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCStorage.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCStorageCopy.h
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCStorageCopy.h
> 
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensor.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensor.h
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorCopy.h
> 
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorRandom.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorMath.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorConv.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorRandom.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorLapack.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorMath.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorConv.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorLapack.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensor.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensor.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorMath.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorMath.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorMathPairwise.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorMathPairwise.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorMathPointwise.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorMathPointwise.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THStorage.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THStorageCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCStorage.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCStorageCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensor.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorRandom.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorMath.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorConv.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorLapack.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensor.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorMath.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorMathPairwise.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorMathPointwise.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THStorage.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THStorageCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCStorage.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCStorageCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensor.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorRandom.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorMath.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorConv.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THTensorLapack.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensor.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorMath.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorMathPairwise.h
> 
> 
> CMake Warning at /usr/share/cmake-3.0/Modules/FindCUDA/make2cmake.cmake:66 (message):
>    Removing non-existent dependency file: generic/THCTensorMathPointwise.h
> 
> 
> /tmp/luarocks_cunn-scm-1-4635/cunn/lib/THCUNN/ELU.cu(40): error: identifier "THCudaTensor_pointwiseApply1" is undefined
> 
> /tmp/luarocks_cunn-scm-1-4635/cunn/lib/THCUNN/ELU.cu(46): error: identifier "THCudaTensor_pointwiseApply2" is undefined
> 
> /tmp/luarocks_cunn-scm-1-4635/cunn/lib/THCUNN/ELU.cu(85): error: identifier "THCudaTensor_pointwiseApply2" is undefined
> 
> /tmp/luarocks_cunn-scm-1-4635/cunn/lib/THCUNN/ELU.cu(91): error: identifier "THCudaTensor_pointwiseApply3" is undefined
> 
> 4 errors detected in the compilation of "/tmp/tmpxft_000079a5_00000000-7_ELU.cpp1.ii".
> CMake Error at THCUNN_generated_ELU.cu.o.cmake:264 (message):
>   Error generating file
>   /tmp/luarocks_cunn-scm-1-4635/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_ELU.cu.o
> 
> 
> lib/THCUNN/CMakeFiles/THCUNN.dir/build.make:63: recipe for target 'lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_ELU.cu.o' failed
> make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_ELU.cu.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> /tmp/luarocks_cunn-scm-1-4635/cunn/lib/THCUNN/SoftPlus.cu(25): error: identifier "THCudaTensor_pointwiseApply2" is undefined
> 
> /tmp/luarocks_cunn-scm-1-4635/cunn/lib/THCUNN/SoftPlus.cu(51): error: identifier "THCudaTensor_pointwiseApply3" is undefined
> 
> 2 errors detected in the compilation of "/tmp/tmpxft_000079b2_00000000-7_SoftPlus.cpp1.ii".
> CMake Error at THCUNN_generated_SoftPlus.cu.o.cmake:264 (message):
>   Error generating file
>   /tmp/luarocks_cunn-scm-1-4635/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SoftPlus.cu.o
> 
> 
> lib/THCUNN/CMakeFiles/THCUNN.dir/build.make:447: recipe for target 'lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_SoftPlus.cu.o' failed
> make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_SoftPlus.cu.o] Error 1
> /tmp/luarocks_cunn-scm-1-4635/cunn/lib/THCUNN/Square.cu(16): error: identifier "THCudaTensor_pointwiseApply2" is undefined
> 
> /tmp/luarocks_cunn-scm-1-4635/cunn/lib/THCUNN/Square.cu(31): error: identifier "THCudaTensor_pointwiseApply3" is undefined
> 
> 2 errors detected in the compilation of "/tmp/tmpxft_000079a9_00000000-7_Square.cpp1.ii".
> CMake Error at THCUNN_generated_Square.cu.o.cmake:264 (message):
>   Error generating file
>   /tmp/luarocks_cunn-scm-1-4635/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_Square.cu.o
> 
> 
> lib/THCUNN/CMakeFiles/THCUNN.dir/build.make:71: recipe for target 'lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_Square.cu.o' failed
> make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_Square.cu.o] Error 1
> CMakeFiles/Makefile2:90: recipe for target 'lib/THCUNN/CMakeFiles/THCUNN.dir/all' failed
> make[1]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/all] Error 2
> Makefile:117: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> Error: Build error: Failed building.

I don't know why it says THCudaTensor_pointwiseApply is undefined. I also followed #265 and added -D_FORCE_INLINES but it's still not working. Thanks!

**Comment by dubvulture** [comment]
I'm experiencing the same issues, minus the initial warnings that should be fixed by installing FindCuda (luarocks install FindCuda)

**Comment by soumith** [comment]
sorry, a commit to cutorch last night broke this. I'm fixing it now.

**Comment by soumith** [comment]
Shhould be fixed now.

**Comment by Henderake** [comment]
It works now. Thanks!

**Comment by ashwani-pandey** [comment]
@soumith Hi, I am having a very similar issue https://github.com/viorik/extracunn/issues/1#issuecomment-226161371 when installing extracunn, and it seems to be that the recent commits you mentioned might be the reason for that.

It would be great if you can help me with that.
