### ISSUE TITLE
cunn installation fails on a fresh Torch distro install on Ubuntu 16.04 TLS

### ISSUE THREAD

**Issue by delip** [torch/cunn#302]
`luarocks install cunn` ends with a compile error:

```
lib/THCUNN/CMakeFiles/THCUNN.dir/build.make:63: recipe for target 'lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_HardTanh.cu.o' failed
make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_HardTanh.cu.o] Error 1
CMakeFiles/Makefile2:103: recipe for target 'lib/THCUNN/CMakeFiles/THCUNN.dir/all' failed
make[1]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.
```

### Steps I've followed so far:

0. rm -Rf ~/torch
1. git clone https://github.com/torch/distro.git ~/torch --recursive
2. cd ~/torch; bash install-deps;
3. ./install.sh
4. luarocks install nn
5. luarocks install cunn

### Environment Variables
```
$ echo $PATH
/home/delip/anaconda2/bin:/home/delip/torch/install/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

```
$ echo $LD_LIBRARY_PATH
/home/delip/torch/install/lib:/usr/local/cuda/lib64:
```

 
### Complete log for `luarocks install cunn`
https://gist.github.com/delip/d6b88b09fc58311b189a024d0fa4e601

**Comment by soumith** [comment]
Excellent. now, can you reinstall cutorch and cunn, via:

luarocks install cutorch 
luarocks install cunn

**Comment by delip** [comment]
That was it! Had to install cutorch before cunn. TY! TY!
