### ISSUE TITLE
Add architecture 6.0 to FindCudaArch.cmake

### ISSUE THREAD

**Issue by CCorfield** [torch/cunn#306]
With the arrival of GTX 1080 cards, and friends, it may make sense to support for 6.0 as a known architecture.

**Comment by soumith** [comment]
does anyone know what all versions I have to add?
6.0 and 6.1? what about 6.2?

**Comment by soumith** [comment]
cc: @borisfom

**Comment by borisfom** [comment]
FindCudaArch.cmake is obsolete and should be removed. 
With the latest distro, new FindCUDA (from CMake 3.6.x) is being installed in share/torch.
cunn already detects that module being installed and selects right arch flags automatically.

**Comment by soumith** [comment]
fixed now via https://github.com/torch/cunn/commit/2b31650c822c0f869758b2fba2c5302bbd414261

**Comment by borisfom** [comment]
A smart way to handle this!

**Comment by CCorfield** [comment]
Thanks!
