### ISSUE TITLE
install cunn by using luarocks install cunn failling

### ISSUE THREAD

**Issue by chelicynly** [torch/cunn#311]
Hi,

When I use "luarocks install cunn" to install cunn, I got the error:  identifier "THCudaBlas_Sgemm" is undefined, shown below.

Installing https://raw.githubusercontent.com/torch/rocks/master/cunn-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cunn-scm-1.rockspec... switching to 'build' mode
Cloning into 'cunn'...
remote: Counting objects: 81, done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 81 (delta 21), reused 20 (delta 3), pack-reused 0
Receiving objects: 100% (81/81), 102.86 KiB | 0 bytes/s, done.
Resolving deltas: 100% (21/21), done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/mcl/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/mcl/torch/install/lib/luarocks/rocks/cunn/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/mcl/torch/install
-- Found CUDA: /usr/local/cuda (found suitable version "7.5", minimum required is "6.5") 
-- Autodetected CUDA architecture(s): 5.2 5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_cunn-scm-1-4745/cunn/build
[  1%] [  3%] [  5%] [  7%] [  9%] [ 11%] [ 13%] [ 15%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_ELU.cu.o
Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialMaxPooling.cu.o
[ 18%] [ 18%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_Threshold.cu.o
Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SoftPlus.cu.o
Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_VolumetricAveragePooling.cu.o
Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_AbsCriterion.cu.o
[ 20%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_ClassNLLCriterion.cu.o
[ 22%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialConvolutionLocal.cu.o
Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_LeakyReLU.cu.o
Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_HardTanh.cu.o
Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_VolumetricConvolution.cu.o
Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_MarginCriterion.cu.o
/tmp/luarocks_cunn-scm-1-4745/cunn/lib/THCUNN/VolumetricConvolution.cu(236): error: identifier "THCudaBlas_Sgemm" is undefined

/tmp/luarocks_cunn-scm-1-4745/cunn/lib/THCUNN/VolumetricConvolution.cu(358): error: identifier "THCudaBlas_Sgemm" is undefined

/tmp/luarocks_cunn-scm-1-4745/cunn/lib/THCUNN/VolumetricConvolution.cu(479): error: identifier "THCudaBlas_Sgemm" is undefined

/tmp/luarocks_cunn-scm-1-4745/cunn/lib/THCUNN/VolumetricConvolution.cu(497): error: identifier "THCudaBlas_Sgemv" is undefined

4 errors detected in the compilation of "/tmp/tmpxft_00006e58_00000000-10_VolumetricConvolution.compute_50.cpp1.ii".
CMake Error at THCUNN_generated_VolumetricConvolution.cu.o.cmake:267 (message):
  Error generating file
  /tmp/luarocks_cunn-scm-1-4745/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_VolumetricConvolution.cu.o

make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_VolumetricConvolution.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

Could you help me about this?

Thanks!

**Comment by soumith** [comment]
Reinstall cutorch first.

**Comment by chelicynly** [comment]
I fixed it. Thanks!
