### ISSUE TITLE
index() - out of bound indices do not throw error for CudaTensors

### ISSUE THREAD

**Issue by lajanugen** [torch/cunn#340]
th> a = torch.rand(3,2):cuda()
                                                                      
th> b = torch.LongTensor({2,4}):cuda()
                                                                     
th> a:index(1,b)
 0.6698  0.7436
 0.1234  0.4400
[torch.CudaTensor of size 2x2]

Index 4 is out of bound in the above, but index() returns some garbage for the corresponding row

**Comment by albanD** [comment]
Please look at these issues on the subject: #167 and #138 (the behaviour of `index` is the same as the one of `LookupTable`)

**Comment by lajanugen** [comment]
Thanks for the pointers, this was helpful!
