### ISSUE TITLE
Error installing cunn

### ISSUE THREAD

**Issue by dearhoper** [torch/cunn#342]
I got the following message when I try to install cunn. 
Before installing cunn, I have successfully installed nn and cutorch. Just prompt: 
Missing dependency for cunnx scm-1: cunn >= 1.0
Missing dependency for inn 1.0-0: cunn

    /home/packages/cunn/lib/THCUNN/VolumetricConvolution.cu(236):
    	
    error: identifier "THCudaBlas_Sgemm" is undefined
    
    /home/packages/cunn/lib/THCUNN/VolumetricConvolution.cu(358): error: identifier "THCudaBlas_Sgemm" is undefined
    
    /home/packages/cunn/lib/THCUNN/VolumetricConvolution.cu(479): error: identifier "THCudaBlas_Sgemm" is undefined
    
    /home/packages/cunn/lib/THCUNN/VolumetricConvolution.cu(497): error: identifier "THCudaBlas_Sgemv" is undefined
    
    4 errors detected in the compilation of "/tmp/tmpxft_00003b52_00000000-10_VolumetricConvolution.compute_30.cpp1.ii".
    /home/packages/cunn/lib/THCUNN/SpatialDilatedConvolution.cu(82): error: identifier "THCudaBlas_Sgemm" is undefined
    
    /home/packages/cunn/lib/THCUNN/SpatialDilatedConvolution.cu(112): error: identifier "THCudaBlas_Sgemm" is undefined
    
    /home/packages/cunn/lib/THCUNN/SpatialDilatedConvolution.cu(192): error: identifier "THCudaBlas_Sgemm" is undefined
    
    /home/packages/cunn/lib/THCUNN/SpatialDilatedConvolution.cu(298): error: identifier "THCudaBlas_Sgemm" is undefined
    
    /home/packages/cunn/lib/THCUNN/SpatialDilatedConvolution.cu(317): error: identifier "THCudaBlas_Sgemv" is undefined
    
    CMake Error at THCUNN_generated_VolumetricConvolution.cu.o.cmake:267 (message):
      Error generating file
      /home/packages/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_VolumetricConvolution.cu.o

    make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_VolumetricConvolution.cu.o] 错误 1
    make[2]: *** 正在等待未完成的任务....
    5 errors detected in the compilation of "/tmp/tmpxft_00003aca_00000000-10_SpatialDilatedConvolution.compute_30.cpp1.ii".
    CMake Error at THCUNN_generated_SpatialDilatedConvolution.cu.o.cmake:267 (message):
      Error generating file
      /home/packages/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialDilatedConvolution.cu.o

    make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_SpatialDilatedConvolution.cu.o] 错误 1
    make[1]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/all] 错误 2
    make: *** [all] 错误 2

    Error: Build error: Failed building.

**Comment by szagoruyko** [comment]
```
luarocks install cutorch
luarocks install cunn
```
