### ISSUE TITLE
ClassNLLCriterion.cu: an illegal memory access was encountered

### ISSUE THREAD

**Issue by uschmelmer** [torch/cunn#345]
Hi,
while training unmodified ENet (https://github.com/e-lab/ENet-training) cityscapes, i get the following error at a random time during 1st or 2nd epoch:

THCudaCheck FAIL file=/home/udo/programs/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu line=171 error=77 : an illegal memory access was encountered /home/udo/programs/torch/install/bin/luajit: cuda runtime error (77) : an illegal memory access was encountered at /home/udo/programs/torch/extra/cutorch/lib/THC/generic/THCStorage.c:147

I am using Ubuntu 16.04 with Cuda 8.0 and a GTX1070 and launch with CUDA_LAUNCH_BLOCKING=1.
Doesn't matter if cudnn is installed via luarocks install or not....

I've read this can happen if classes are out of bounds, but i think it's not the case in this code.

Best Regards,
Udo

**Comment by soumith** [comment]
are you sure that's not the case? I cant think of any reason really, where in that code things will go out of bounds othewise.
Any test case to reproduce this if not?

**Comment by uschmelmer** [comment]
So they have a #classes of 20 in data/loadCityscape.lua . And the classes are distributed from 1-20. So I think they are within the bounds. Or did i misunderstand something?
Best Regards,
Udo

**Comment by soumith** [comment]
maybe your dataset is corrupt or something. 
Have a print statement that prints out the min and max of your class targets for every mini-batch (they will be a number between 1 and 20). Right before it crashes, you will see that this number will be < 1 or > 20

**Comment by uschmelmer** [comment]
Thanks, i will try it and report. But can take one or two days.

**Comment by uschmelmer** [comment]
Hi, i was due to a corrupt Path to the dataset. The Database was created with All classes beeing zero, but the Code did Not give any error until the Crash after some time.

Best Regards,
Udo
