### ISSUE TITLE
error when using cunn

### ISSUE THREAD

**Issue by cosmozhang** [torch/cunn#348]
Ubuntu 14.04
Cuda7.5
GTX980

I got this error when trying to use cunn, though cutorch is correct:
luajit: error loading module 'libcunn' from file '/home/zhang923/.luarocks/lib/lua/5.1/libcunn.so':
        /home/zhang923/.luarocks/lib/lua/5.1/libcunn.so: undefined symbol: THCudaBlas_gemv
stack traceback:
        [C]: at 0x0047aff0
        [C]: in function 'require'
        /home/zhang923/.luarocks/share/lua/5.1/cunn/init.lua:3: in main chunk
        [C]: at 0x0046b7a0
        [C]: at 0x00406670
*** Error in `luajit': corrupted double-linked list: 0x00000000019cf7a0 ***
Aborted (core dumped)

I will appreciate any help here! Thank you!

**Comment by soumith** [comment]
this indicates that your cutorch is out of date.
luarocks install cutorch
luarocks install cunn

**Comment by cosmozhang** [comment]
That is what I tried, but the problem was not resolved...

**Comment by soumith** [comment]
you seem to have a locally installed cunn.

Run this command first:

rm -rf ~/.luarocks

**Comment by cosmozhang** [comment]
Hi Dear soumith, thank you for the help. I found the problem. Nvidia cuda installation pack cuda_7.5.18_linux.run does not create symbolic links libcublas.so -> libcublas.so.7.5 and libcublas.so.7.5->libcublas.so.7.5.18 correctly. I have to delete the old files created by the installation and create correct symbolic links manual. Now it is solve.
