### ISSUE TITLE
build failed at git checkout 3f5a8ba2bd4e6babf112d6369c98f37be86d2391

### ISSUE THREAD

**Issue by loveJasmine** [torch/cunn#349]
andy1028@andy1028-Envy:/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn$ git checkout 3f5a8ba2bd4e6babf112d6369c98f37be86d2391
HEAD is now at 3f5a8ba... add SpatialCrossMapLRN
andy1028@andy1028-Envy:/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn$ luarocks make rocks/cunn-scm-1.rockspec
Warning: unmatched variable LUALIB
cmake -E make_directory build && cd build && cmake .. -DLUALIB= -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/andy1028/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/andy1028/torch/install/lib/luarocks/rocks/cunn/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- Found Torch7 in /home/andy1028/torch/install
-- Compiling for CUDA architecture: 5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/build
[  2%] [  4%] [  7%] [  9%] [ 12%] [ 14%] [ 19%] [ 19%] Building NVCC (Device) object CMakeFiles/cunn.dir//./cunn_generated_VolumetricMaxPooling.cu.o
Building NVCC (Device) object CMakeFiles/cunn.dir//./cunn_generated_Abs.cu.o
Building NVCC (Device) object CMakeFiles/cunn.dir//./cunn_generated_SpatialFractionalMaxPooling.cu.o
Building NVCC (Device) object CMakeFiles/cunn.dir//./cunn_generated_ELU.cu.o
Building NVCC (Device) object CMakeFiles/cunn.dir//./cunn_generated_HardTanh.cu.o
Building NVCC (Device) object CMakeFiles/cunn.dir//./cunn_generated_LeakyReLU.cu.o
Building NVCC (Device) object CMakeFiles/cunn.dir//./cunn_generated_LookupTable.cu.o
Building NVCC (Device) object CMakeFiles/cunn.dir//./cunn_generated_LogSigmoid.cu.o
/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/LogSigmoid.cu(20): error: identifier "THCudaTensor_pointwiseApply2" is undefined

/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/LogSigmoid.cu(41): error: identifier "THCudaTensor_pointwiseApply3" is undefined

/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/Abs.cu(19): error: identifier "THCudaTensor_pointwiseApply2" is undefined

/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/Abs.cu(39): error: identifier "THCudaTensor_pointwiseApply3" is undefined

/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/VolumetricMaxPooling.cu(26): error: identifier "THInf" is undefined

/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/LeakyReLU.cu(37): error: identifier "THCudaTensor_pointwiseApply1" is undefined

/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/LeakyReLU.cu(42): error: identifier "THCudaTensor_pointwiseApply2" is undefined

/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/LeakyReLU.cu(87): error: identifier "THCudaTensor_pointwiseApply2" is undefined

/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/LeakyReLU.cu(92): error: identifier "THCudaTensor_pointwiseApply3" is undefined

/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/HardTanh.cu(32): error: identifier "THCudaTensor_pointwiseApply2" is undefined

/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/HardTanh.cu(65): error: identifier "THCudaTensor_pointwiseApply3" is undefined

/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/ELU.cu(24): error: identifier "THCudaTensor_pointwiseApply2" is undefined

/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/ELU.cu(49): error: identifier "THCudaTensor_pointwiseApply3" is undefined

/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/SpatialFractionalMaxPooling.cu(44): error: identifier "THInf" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00001ee9_00000000-7_SpatialFractionalMaxPooling.cpp1.ii".
2 errors detected in the compilation of "/tmp/tmpxft_00001f07_00000000-7_LogSigmoid.cpp1.ii".
CMake Error at cunn_generated_SpatialFractionalMaxPooling.cu.o.cmake:267 (message):
  Error generating file
  /media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/build/CMakeFiles/cunn.dir//./cunn_generated_SpatialFractionalMaxPooling.cu.o

CMakeFiles/cunn.dir/build.make:428: recipe for target 'CMakeFiles/cunn.dir/./cunn_generated_SpatialFractionalMaxPooling.cu.o' failed
make[2]: *** [CMakeFiles/cunn.dir/./cunn_generated_SpatialFractionalMaxPooling.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
2 errors detected in the compilation of "/tmp/tmpxft_00001efd_00000000-7_Abs.cpp1.ii".
CMake Error at cunn_generated_LogSigmoid.cu.o.cmake:267 (message):
  Error generating file
  /media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/build/CMakeFiles/cunn.dir//./cunn_generated_LogSigmoid.cu.o

CMakeFiles/cunn.dir/build.make:3875: recipe for target 'CMakeFiles/cunn.dir/./cunn_generated_LogSigmoid.cu.o' failed
make[2]: *** [CMakeFiles/cunn.dir/./cunn_generated_LogSigmoid.cu.o] Error 1
CMake Error at cunn_generated_Abs.cu.o.cmake:267 (message):
  Error generating file
  /media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/build/CMakeFiles/cunn.dir//./cunn_generated_Abs.cu.o

CMakeFiles/cunn.dir/build.make:620: recipe for target 'CMakeFiles/cunn.dir/./cunn_generated_Abs.cu.o' failed
make[2]: *** [CMakeFiles/cunn.dir/./cunn_generated_Abs.cu.o] Error 1
/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/VolumetricMaxPooling.cu(77): error: identifier "THInf" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00001ef5_00000000-7_VolumetricMaxPooling.cpp1.ii".
4 errors detected in the compilation of "/tmp/tmpxft_00001f0a_00000000-7_LeakyReLU.cpp1.ii".
2 errors detected in the compilation of "/tmp/tmpxft_00001f0f_00000000-7_HardTanh.cpp1.ii".
CMake Error at cunn_generated_VolumetricMaxPooling.cu.o.cmake:267 (message):
  Error generating file
  /media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/build/CMakeFiles/cunn.dir//./cunn_generated_VolumetricMaxPooling.cu.o

CMakeFiles/cunn.dir/build.make:4306: recipe for target 'CMakeFiles/cunn.dir/./cunn_generated_VolumetricMaxPooling.cu.o' failed
make[2]: *** [CMakeFiles/cunn.dir/./cunn_generated_VolumetricMaxPooling.cu.o] Error 1
CMake Error at cunn_generated_LeakyReLU.cu.o.cmake:267 (message):
  Error generating file
  /media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/build/CMakeFiles/cunn.dir//./cunn_generated_LeakyReLU.cu.o

CMakeFiles/cunn.dir/build.make:3867: recipe for target 'CMakeFiles/cunn.dir/./cunn_generated_LeakyReLU.cu.o' failed
make[2]: *** [CMakeFiles/cunn.dir/./cunn_generated_LeakyReLU.cu.o] Error 1
CMake Error at cunn_generated_HardTanh.cu.o.cmake:267 (message):
  Error generating file
  /media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/build/CMakeFiles/cunn.dir//./cunn_generated_HardTanh.cu.o

CMakeFiles/cunn.dir/build.make:2435: recipe for target 'CMakeFiles/cunn.dir/./cunn_generated_HardTanh.cu.o' failed
make[2]: *** [CMakeFiles/cunn.dir/./cunn_generated_HardTanh.cu.o] Error 1
2 errors detected in the compilation of "/tmp/tmpxft_00001f05_00000000-7_ELU.cpp1.ii".
CMake Error at cunn_generated_ELU.cu.o.cmake:267 (message):
  Error generating file
  /media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/build/CMakeFiles/cunn.dir//./cunn_generated_ELU.cu.o

CMakeFiles/cunn.dir/build.make:2243: recipe for target 'CMakeFiles/cunn.dir/./cunn_generated_ELU.cu.o' failed
make[2]: *** [CMakeFiles/cunn.dir/./cunn_generated_ELU.cu.o] Error 1
/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/LookupTable.cu(179): error: argument of type "THCudaTensor *" is incompatible with parameter of type "THCudaLongTensor *"

1 error detected in the compilation of "/tmp/tmpxft_00001f2e_00000000-7_LookupTable.cpp1.ii".
CMake Error at cunn_generated_LookupTable.cu.o.cmake:267 (message):
  Error generating file
  /media/andy1028/data1t/os_prj/github/SNLI-attention/cunn/build/CMakeFiles/cunn.dir//./cunn_generated_LookupTable.cu.o

CMakeFiles/cunn.dir/build.make:3883: recipe for target 'CMakeFiles/cunn.dir/./cunn_generated_LookupTable.cu.o' failed
make[2]: *** [CMakeFiles/cunn.dir/./cunn_generated_LookupTable.cu.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/cunn.dir/all' failed
make[1]: *** [CMakeFiles/cunn.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.
andy1028@andy1028-Envy:/media/andy1028/data1t/os_prj/github/SNLI-attention/cunn$

**Comment by fmassa** [comment]
You need to update `cutorch` as well. Just in case, run
```
luarocks install torch
luarocks install cutorch
luarocks install nn
luarocks install cunn
```

**Comment by loveJasmine** [comment]
not works yet

**Comment by BTNC** [comment]
@loveJasmine , you are checking out a commit on 25 Dec 2015. What is blocking you from using the up-to-date master branch? If you still want to use cunn on that commit, I am afraid you will need to checkout torch, cutorch, nn repositories on the same date, that is 25 Dec 2015. Otherwise, there will be no guarantee old cunn could compile against up-to-date torch.

**Comment by loveJasmine** [comment]
just for run 
https://github.com/cheng6076/SNLI-attention.git
