### ISSUE TITLE
Unable to build an older version.

### ISSUE THREAD

**Issue by Achilles-96** [torch/cunn#359]
I posted on google group but got no reply. This is the link - https://groups.google.com/forum/#!topic/torch7/jIyveGldcE0

**Comment by fmassa** [comment]
You also need to downgrade cutorch before other types were introduced. You might need to try a bit, but I'd start with this commit https://github.com/torch/cutorch/commit/aa9dd6e08ac3d5aea5643ef26f2fcf10d9b076a6

**Comment by Achilles-96** [comment]
Hello, it is hard to find the commit. Can you please tell the exact commit id.

**Comment by fmassa** [comment]
@Achilles-96 I'd first try with this commit: aa9dd6e08ac3d5aea5643ef26f2fcf10d9b076a6

**Comment by soumith** [comment]
as replied on the google group:

Well, in that case cutorch depends on a torch commit as well.
Here's my recommendation.
Erase your torch, and do this:

```bash
git clone https://github.com/torch/distro ~/torch
cd ~/torch
git reset --hard 99081d95148631c581891d74e626d09078895a93 # commit hash from Dec 19th
./install.sh
```

**Comment by Achilles-96** [comment]
That version does not build.
![screenshot_20161104_210443](https://cloud.githubusercontent.com/assets/10742413/20011704/8816181e-a2d2-11e6-8582-17ef828437da.png)
