### ISSUE TITLE
Potential performance issue with "LookupTable", feature request

### ISSUE THREAD

**Issue by frankang** [torch/cunn#387]
Hi, 
I encountered an performance issue when trying to speed up the beam search process within the [seq2seq-attn](https://github.com/harvardnlp/seq2seq-attn) project.
Below is a scratched code to show this.

```lua
--code begin--
require "nngraph"
require "cunn"
require "cutorch"
require "os"
cutorch.setDevice(1)
t1=torch.Timer():stop():reset()
t2=torch.Timer():stop():reset()
i=1

----------create module------
input=nn.Identity()()
i = nn.LookupTable(40000,500)(input)
j = nn.Linear(500,4000)(i)
k=nn.Tanh()(j)
l=nn.Linear(4000,1000,fasle)(k)
m=nn.LogSoftMax()(l)
module=nn.gModule({input},{m})
torch.save("testmodule",module)
print("module saved")
----------load module ------
temp=torch.load("testmodule")
temp:cuda()
--temp:forward(torch.LongTensor({4}))
--print("done")

local y,index
index = torch.LongTensor({4})
i=1
while i <300 do
  i=i+1
  t1:resume()
  local dst = temp:forward(index)
  cutorch.synchronize()
  t1:stop()

  t2:resume()
  local flatdst=dst:view(-1)
  y,index=flatdst:max(1)

  --uncomment the following line to see time difference
  local daa= index[1]
  cutorch.synchronize()
  t2:stop()
end
print("step1 timer "..t1:time().real)
print("step2 timer "..t2:time().real)

os.remove("testmodule")
--code end--
```
Basically I was trying to profile the lua code, and I found that when
> local daa= index[1] --is uncommented and executed

the output is 
step1 timer 0.15371942520142
step2 timer 0.29980826377869

The step2 time is large which I considered as the GPU memory data transfer. But when 
> -- local daa= index[1] --is commented 

the output on my computer is 
step1 timer 0.30201196670532
step2 timer 0.021998882293701
Without the querying elements ([index]) operation, the step 2 time was indeed reduced, but the forward time (step1 timer) got expanded to 2X more . I am puzzled by this stuff so I raise it here. 
If it is not appropriate to post here, feel free to delete this issue.
Thanks.

**Comment by soumith** [comment]
before every time().real, you need to call cutorch.synchronize(), otherwise your timings will be wrong.

**Comment by frankang** [comment]
Did you mean this?

> cutorch.synchronize()
print("step1 timer "..t1:time().real)
cutorch.synchronize()
print("step2 timer "..t2:time().real)

But after the above modification, the timings are merely changed.

**Comment by soumith** [comment]
i've inserted cutorch.synchronize() to your script above in the correct places.
Yours is def a benchmarking issue and not a true perf issue from your script.
Reopen the issue if you find otherwise.
