### ISSUE TITLE
Can't install cunn

### ISSUE THREAD

**Issue by LorenzoPoli** [torch/cunn#388]
Hi, I tried to install cunn on my machine (Linux Mint 17.2 Rafaela (GNU/Linux 3.16.0-38-generic x86_64)
, GPU Tesla C2070, CUDA 7.5 installed), but I got the follwing error:

Error generating
  /tmp/luarocks_cunn-scm-1-CscMTx/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_ELU.cu.o

In file included from /tmp/luarocks_cunn-scm-1-CscMTx/cunn/lib/THCUNN/SpatialMaxUnpooling.cu:1:0:
/tmp/luarocks_cunn-scm-1-CscMTx/cunn/lib/THCUNN/THCUNN.h:11:35: fatal error: THCGenerateFloatTypes.h: No such file or directory
 #include "THCGenerateFloatTypes.h"
                                   ^
compilation terminated.
In file included from /tmp/luarocks_cunn-scm-1-CscMTx/cunn/lib/THCUNN/SpatialAdaptiveMaxPooling.cu:1:0:
/tmp/luarocks_cunn-scm-1-CscMTx/cunn/lib/THCUNN/THCUNN.h:11:35: fatal error: THCGenerateFloatTypes.h: No such file or directory
 #include "THCGenerateFloatTypes.h"
                                   ^
compilation terminated.
make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_ELU.cu.o] Error 1
CMake Error at THCUNN_generated_SpatialAdaptiveMaxPooling.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cunn-scm-1-CscMTx/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialAdaptiveMaxPooling.cu.o

CMake Error at THCUNN_generated_SpatialMaxUnpooling.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cunn-scm-1-CscMTx/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialMaxUnpooling.cu.o

make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_SpatialAdaptiveMaxPooling.cu.o] Error 1
make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_SpatialMaxUnpooling.cu.o] Error 1
In file included from /tmp/luarocks_cunn-scm-1-CscMTx/cunn/lib/THCUNN/Square.cu:1:0:
/tmp/luarocks_cunn-scm-1-CscMTx/cunn/lib/THCUNN/THCUNN.h:11:35: fatal error: THCGenerateFloatTypes.h: No such file or directory
 #include "THCGenerateFloatTypes.h"
                                   ^
compilation terminated.
CMake Error at THCUNN_generated_Square.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_cunn-scm-1-CscMTx/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_Square.cu.o

make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_Square.cu.o] Error 1
make[1]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

I tried to reinstall torch, nn and cutorch (luarocks install torch ecc), as suggested on other issues, but even if they don't have any problem, cunn installation give me the same error.
Any suggestions? Thanks in advance
Lorenzo

**Comment by soumith** [comment]
hey Lorenzo,

It looks like you are missing THCGenerateFloatTypes.h: No such file or directory
this points to the fact that you have an outdated cutorch.
Maybe the outdated cutorch is in some unexpected location on your machine and is being picked up by cmake.

I'd suggest first running: https://github.com/torch/ezinstall/blob/master/clean-old.sh

then: luarocks install cutorch
and then: luarocks install cunn

**Comment by LorenzoPoli** [comment]
Solved, the issue was the same as: https://github.com/torch/cutorch/pull/592
