### ISSUE TITLE
Error: calling a host function operator != from global function is not allowed

### ISSUE THREAD

**Issue by archenroot** [torch/cunn#391]
On Gentoo tried to compile with multiple GCC 4.9, 5.4 or 6.2(save flags enabled like -g -fno-delete-null-pointer-checks -std=gnu+=98)
CUDA 8.0
dev-libs/nvidia-cuda-cudnn 8.0 compatible (5.1 version)

/tmp/portage/sci-libs/torch-cunn-9999/work/torch-cunn-9999/lib/THCUNN/SpatialFractionalMaxPooling.cu(77): error: calling a __host__ function("operator !=") from a __global__ function("SpatialFractionalMaxPooling_updateOutput<(int)2,  ::__half, float> ") is not allowed

/tmp/portage/sci-libs/torch-cunn-9999/work/torch-cunn-9999/lib/THCUNN/SpatialFractionalMaxPooling.cu(77): error: calling a __host__ function("operator !=") from a __global__ function("SpatialFractionalMaxPooling_updateOutput<(int)3,  ::__half, float> ") is not allowed

/tmp/portage/sci-libs/torch-cunn-9999/work/torch-cunn-9999/lib/THCUNN/SpatialFractionalMaxPooling.cu(77): error: calling a __host__ function("operator !=") from a __global__ function("SpatialFractionalMaxPooling_updateOutput<(int)4,  ::__half, float> ") is not allowed

/tmp/portage/sci-libs/torch-cunn-9999/work/torch-cunn-9999/lib/THCUNN/SpatialFractionalMaxPooling.cu(77): error: calling a __host__ function("operator !=") from a __global__ function("SpatialFractionalMaxPooling_updateOutput<(int)5,  ::__half, float> ") is not allowed

/tmp/portage/sci-libs/torch-cunn-9999/work/torch-cunn-9999/lib/THCUNN/SpatialFractionalMaxPooling.cu(77): error: calling a __host__ function("operator !=") from a __global__ function("SpatialFractionalMaxPooling_updateOutput<(int)6,  ::__half, float> ") is not allowed

/tmp/portage/sci-libs/torch-cunn-9999/work/torch-cunn-9999/lib/THCUNN/SpatialFractionalMaxPooling.cu(77): error: calling a __host__ function("operator !=") from a __global__ function("SpatialFractionalMaxPooling_updateOutput<(int)7,  ::__half, float> ") is not allowed

/tmp/portage/sci-libs/torch-cunn-9999/work/torch-cunn-9999/lib/THCUNN/SpatialFractionalMaxPooling.cu(77): error: calling a __host__ function("operator !=") from a __global__ function("SpatialFractionalMaxPooling_updateOutput<(int)-1,  ::__half, float> ") is not allowed

**Comment by soumith** [comment]
should be fixed in master. 
Running this command should work now:
luarocks install cunn

**Comment by archenroot** [comment]
Aha, I just woke and was able to downgrade CUDA to 7.5 and CUDNN to 7.0, and it finished without issues, but I had to switch from GCC 5.4 or 6.2 to 4.9 as cutorch failed on:
/opt/cuda/include/host_config.h:115:2: error: #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
 #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!

When keeping GCC 4.9 with CUDA to 7.5 and CUDNN to 7.0, that works as expected stable env config.

I am going now trying back your fix with latest GCC 6.2, for incompatible packages I have environmental safe switch:
CXXFLAGS="${CXXFLAGS} -g -fno-delete-null-pointer-checks -std=gnu++98 -flifetime-dse=1 -fno-delete-null-pointer-checks -fpermissive"

If that won't work I will try fallback to 5.4 and report result here.

**Comment by archenroot** [comment]
Ok, so I switched back to GCC 6.2.0 r1(i have all three compiled at same time anyway, so easy task) with global CFLAGS optimized for Skylake processor:
`CFLAGS="-march=skylake -mabm -maes -madx -mrtm"
CFLAGS="${CFLAGS} -mavx256-split-unaligned-load -mavx256-split-unaligned-store"
CFLAGS="${CFLAGS} --param l1-cache-line-size=64 --param l1-cache-size=32 --param l2-cache-size=6144"
CFLAGS="${CFLAGS} -O2 -pipe"`

I succesfully installed following packages in order:
`dev-util/nvidia-cuda-toolkit-8.0.44`

Installing cutorc failed on unsupported GNU version:
/opt/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!

I tried to change to manually override in /opt/cuda/include/host_config.h from:
#if __GNUC__ > 5
to:
#if __GNUC__ > 6
:dancer: 

But there happen dozen of weird errors while compiling cutorch all similar to this snippet:

> -- Generating /tmp/portage/sci-libs/torch-cutorch-9999/work/torch-cutorch-9999_build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o
> /opt/cuda/bin/nvcc /tmp/portage/sci-libs/torch-cutorch-9999/work/torch-cutorch-9999/lib/THC/THCBlas.cu -c -o /tmp/portage/sci-libs/torch-cutorch-9999/work/torch-cutorch-9999_build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o -ccbin /usr/bin/x86_64-pc-linux-gnu-gcc -m64 -DTHC_EXPORTS -Xcompiler ,\"-march=skylake\",\"-mabm\",\"-maes\",\"-madx\",\"-mrtm\",\"-mavx256-split-unaligned-load\",\"-mavx256-split-unaligned-store\",\"--param\",\"l1-cache-line-size=64\",\"--param\",\"l1-cache-size=32\",\"--param\",\"l2-cache-size=6144\",\"-O2\",\"-pipe\",\"-fPIC\" -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_61,code=compute_61 -DCUDA_HAS_FP16=1 -DNVCC -I/opt/cuda/include -I/usr/include/luajit-2.0 -I/usr/include/luajit-2.0/TH -I/opt/cuda/include -I/tmp/portage/sci-libs/torch-cutorch-9999/work/torch-cutorch-9999/lib/THC/CUDA_SDK_ROOT_DIR-NOTFOUND/common/inc -I/TH -I/tmp/portage/sci-libs/torch-cutorch-9999/work/torch-cutorch-9999/lib/THC -I/tmp/portage/sci-libs/torch-cutorch-9999/work/torch-cutorch-9999_build/lib/THC
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/stddef.h(436): error: identifier "nullptr" is undefined
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/stddef.h(436): error: expected a ";"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/x86_64-pc-linux-gnu/bits/c++config.h(202): error: expected a ";"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/exception(63): error: expected a ";"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/exception(69): error: expected a ";"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/exception(77): error: expected a ";"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/exception(85): error: expected a ";"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/exception(95): error: expected a "{"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/bits/exception_ptr.h(64): error: function "std::current_exception" returns incomplete type "std::__exception_ptr::exception_ptr"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/bits/exception_ptr.h(64): error: expected a "{"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/bits/exception_ptr.h(71): error: namespace "std" has no member "rethrow_exception"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/bits/exception_ptr.h(81): error: expected a ";"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/bits/exception_ptr.h(83): error: expected a ";"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/bits/exception_ptr.h(84): error: expected a ";"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/bits/exception_ptr.h(86): error: expected a ";"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/bits/exception_ptr.h(88): error: declaration is incompatible with previous "std::current_exception"
> (64): here
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/bits/exception_ptr.h(88): error: use of a local type to declare a function
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/bits/exception_ptr.h(88): error: expected a ";"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/bits/exception_ptr.h(89): error: use of a local type to declare a function
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/bits/exception_ptr.h(92): error: expected a ";"
> 
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/g++-v6/bits/exception_ptr.h(94): error: expected a ";"
> 

So I made an exception for cutorch backend package by application of those safe CXXFLAGS switches from previous post and compiled successfully cutorch, but remember I manually overrided CUDA toolkit host_config header file.

Now I jumped onto torch-cunn package finally again I went with GCC safe switches and all works now, going to test torch.

Thanks for support!

Ladislav
