### ISSUE TITLE
unable to convert argument 3 from cdata<struct THCudaLongTensor*> to cdata<struct THCudaTensor*>

### ISSUE THREAD

**Issue by pby5** [torch/cunn#404]
when I use crossEntropy:forward(conf_out,conf_target) in my code and it exists an error: and I had tensors to cuda already.

/home/gavinpan/torch/install/bin/lua: unable to convert argument 3 from cdata<struct THCudaLongTensor*> to cdata<struct THCudaTensor*>
stack traceback:
	[C]: in function 'v'
	/home/gavinpan/torch/install/share/lua/5.2/nn/THNN.lua:110: in function 'ClassNLLCriterion_updateOutput'
	...pan/torch/install/share/lua/5.2/nn/ClassNLLCriterion.lua:43: in function 'updateOutput'
	...torch/install/share/lua/5.2/nn/CrossEntropyCriterion.lua:13: in function <...torch/install/share/lua/5.2/nn/CrossEntropyCriterion.lua:9>
	(...tail calls...)
	train.lua:402: in function 'opfunc'
	/home/gavinpan/torch/install/share/lua/5.2/optim/sgd.lua:44: in function 'optimMethod'

**Comment by soumith** [comment]
your nn is likely out of date.
luarocks install nn

that will fix it.
