### ISSUE TITLE
batched MM does not work on FP16

### ISSUE THREAD

**Issue by jsenellart-systran** [torch/cunn#417]
not sure if this issue should be reported in cunn or cutorch. 

### Issue
The problem is the following - the following script:

```
require "cunn"
model=nn.MM():type('torch.CudaHalfTensor')
A=torch.CudaHalfTensor(10,20,30)
B=torch.CudaHalfTensor(10,30,40)
model:forward({A,B})
```

=> generate the error: torch/install/share/lua/5.2/nn/MM.lua:42: unimplemented data type at /home/devling/projects/onmt-js/torch/extra/cutorch/lib/THC/generic/THCTensorMathBlas.cu:596

It works for regular CudaTensor.

This issue causes nn.Linear not working.

### Analysis

- in THCTensorMathBlas.cu - the function `THCTensor_(baddbmm)` is indeed missing the support of HALF, 
- and going deeper, it comes from THCBlas.cu which has implementation of `THCudaBlas_SgemmBatched` and `THCudaBlas_DgemmBatched` but not `THCudaBlas_HgemmBatched `
- which in turns come from missing `cublasHgemmBatched` cuda primitive [here page 69](http://docs.nvidia.com/cuda/pdf/CUDA_CUBLAS_Users_Guide.pdf)

### Fix
we can workaround batched MM with regular MM - is it the solution, is there another alternative - at which level should it be fixed?

**Comment by soumith** [comment]
the naive fix is that we just do a for-loop in the case of half.
cc: @gchanan

**Comment by gchanan** [comment]
You are correct on the issue; In general I left unimplemented those functions that did not have an existing efficient cuda implementation.  In this case we should probably just implement in cutorch with a comment that we should use the cublas version if it ever becomes available.

**Comment by jsenellart-systran** [comment]
Hi @gchanan, just to check - do you plan to implement this or do you prefer we send you a PR?

**Comment by gchanan** [comment]
please send a PR :).
