### ISSUE TITLE
Cannot install cunn

### ISSUE THREAD

**Issue by rward88** [torch/cunn#436]
Torch and cutorch both installed successfully, but installing cunn via luarocks has failed repeatedly.  This is on Ubuntu 16

Warning: unmatched variable LUALIB
cmake -E make_directory build && cd build && cmake .. -DLUALIB= -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/rward/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/rward/torch/install/lib/luarocks/rocks/cunn/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/rward/torch/install
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "6.5") 
-- Removing -DNDEBUG from compile flags
-- TH_LIBRARIES: TH
-- THC_LIBRARIES: THC
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;6.0;6.1;6.1+PTX
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    LUALIB

-- Build files have been written to: /home/rward/torch/cunn/build
[  1%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_LookupTable.cu.o
[  3%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SpatialMaxUnpooling.cu.o
[  5%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_VolumetricAveragePooling.cu.o
[  6%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SpatialClassNLLCriterion.cu.o
[  8%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_RReLU.cu.o
[ 10%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_GatedLinearUnit.cu.o
[ 11%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_MultiLabelMarginCriterion.cu.o
[ 13%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_Threshold.cu.o
[ 15%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_MarginCriterion.cu.o
[ 16%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SpatialUpSamplingNearest.cu.o
[ 18%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SpatialConvolutionLocal.cu.o
[ 20%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_HardTanh.cu.o
/home/rward/torch/cunn/lib/THCUNN/generic/GatedLinearUnit.cu(27): error: identifier "THC_pointwiseApply3" is undefined

/home/rward/torch/cunn/lib/THCUNN/generic/GatedLinearUnit.cu(53): error: identifier "THC_pointwiseApply3" is undefined

/home/rward/torch/cunn/lib/THCUNN/generic/GatedLinearUnit.cu(27): error: identifier "THC_pointwiseApply3" is undefined

/home/rward/torch/cunn/lib/THCUNN/generic/GatedLinearUnit.cu(53): error: identifier "THC_pointwiseApply3" is undefined

/home/rward/torch/cunn/lib/THCUNN/generic/GatedLinearUnit.cu(27): error: identifier "THC_pointwiseApply3" is undefined

/home/rward/torch/cunn/lib/THCUNN/generic/GatedLinearUnit.cu(53): error: identifier "THC_pointwiseApply3" is undefined

6 errors detected in the compilation of "/tmp/tmpxft_00007f9b_00000000-17_GatedLinearUnit.compute_61.cpp1.ii".
CMake Error at THCUNN_generated_GatedLinearUnit.cu.o.cmake:267 (message):
  Error generating file
  /home/rward/torch/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_GatedLinearUnit.cu.o

lib/THCUNN/CMakeFiles/THCUNN.dir/build.make:91: recipe for target 'lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_GatedLinearUnit.cu.o' failed
make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_GatedLinearUnit.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:103: recipe for target 'lib/THCUNN/CMakeFiles/THCUNN.dir/all' failed
make[1]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by soumith** [comment]
@rward88 sorry about this. fixed via https://github.com/torch/cunn/pull/437
