### ISSUE TITLE
not found: THNN_CudaDoubleGatedLinear_updateOutput...

### ISSUE THREAD

**Issue by guopei** [torch/cunn#439]
I just updated my torch installation using update.sh, then uses luarocks to install nn, cunn, cutorch, cudnn, etc..
But every time I require 'cunn', the following message came out:

`not found: THNN_CudaDoubleGatedLinear_updateOutput...peiguo/torch/new-torch/install/share/lua/5.1/nn/THNN.lua:108: /scratch/peiguo/torch/new-torch/install/lib/lua/5.1/libTHCUNN.so: undefined symbol: THNN_CudaDoubleGatedLinear_updateOutput
not found: THNN_CudaDoubleGatedLinear_updateGradInput...peiguo/torch/new-torch/install/share/lua/5.1/nn/THNN.lua:108: /scratch/peiguo/torch/new-torch/install/lib/lua/5.1/libTHCUNN.so: undefined symbol: THNN_CudaDoubleGatedLinear_updateGradInput
not found: THNN_CudaHalfGatedLinear_updateOutput...peiguo/torch/new-torch/install/share/lua/5.1/nn/THNN.lua:108: /scratch/peiguo/torch/new-torch/install/lib/lua/5.1/libTHCUNN.so: undefined symbol: THNN_CudaHalfGatedLinear_updateOutput
not found: THNN_CudaHalfGatedLinear_updateGradInput...peiguo/torch/new-torch/install/share/lua/5.1/nn/THNN.lua:108: /scratch/peiguo/torch/new-torch/install/lib/lua/5.1/libTHCUNN.so: undefined symbol: THNN_CudaHalfGatedLinear_updateGradInput`

Anybody knows why this happens? Thanks!

**Comment by soumith** [comment]
@guopei can you try running this command:
```
luarocks install cunn
```
and afterwards retry

**Comment by guopei** [comment]
Thanks for your answer.

I tried
`
luarocks install nn
luarocks install cutorch
luarocks install cunn
luarocks install cudnn
`
basically I have reinstalled everything I think. But this message always appears. I know this Gated Linear layer is newly added from the commit history. I can't figure out the reason why it cannot find the functions as it's indeed defined in GatedLinearUnit.cu and THCUNN.h

**Comment by pavanky** [comment]
@guopei Any chance you have multiple installed versions ?

**Comment by guopei** [comment]
It could be, but I checked by luarocks list, it only shows one cunn version
installed...

**Comment by gchanan** [comment]
I was able to reproduce this.

https://github.com/torch/cunn/pull/440 should fix it.

**Comment by soumith** [comment]
thanks for fixing it greg!
