### ISSUE TITLE
wrong number of arguments for function call with ClassNLLCriterion

### ISSUE THREAD

**Issue by anoidgit** [torch/cunn#471]
I have tried these code:
```
tcrit=nn.ClassNLLCriterion():cuda()
id=torch.randn(4):cuda()
td=torch.LongTensor({2}):cudaLong()
tcrit:forward(id, td)
```
and it reports this:
```
/usr/local/share/lua/5.1/nn/THNN.lua:110: wrong number of arguments for function call
stack traceback:
	[C]: in function 'v'
	/usr/local/share/lua/5.1/nn/THNN.lua:110: in function 'ClassNLLCriterion_updateOutput'
	/usr/local/share/lua/5.1/nn/ClassNLLCriterion.lua:43: in function 'forward'
	[string "_RESULT={tmod:forward(id, td)}"]:1: in main chunk
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/trepl/init.lua:661: in function 'repl'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
	[C]: at 0x004057a0
```

**Comment by anoidgit** [comment]
I find their is a commit to related files 15 days ago, so I have reinstalled torch, nn and cunn, but it still can not work.

**Comment by anoidgit** [comment]
I have try to remove calls to `cuda()` to run it on cpu, it can correctly work on cpu.

**Comment by anoidgit** [comment]
I remove the package and reinstall it, this is fixed.

**Comment by zcrwind** [comment]
Hi, I have met the same problem while using Torch and nn module, could you please tell me which package you have reinstalled? I reinstall the torch and `nn` by running `luarocks install torch` and `luarocks install nn`, sadly, it did not work...

**Comment by zcrwind** [comment]
@anoidgit Hi, I have met the same problem while using Torch and `nn` module, could you please tell me which package do you have reinstalled? I reinstall the torch and `nn` by running `luarocks install torch` and `luarocks install nn`, sadly, it did not work...

**Comment by anoidgit** [comment]
I have removed the package and related files in the rocks path, before I use `luarocks install` command to reinstall these libraries. @zcrwind
