### ISSUE TITLE
Problems while Compiling with CUDA11, Ubuntu 20.04

### ISSUE THREAD

**Issue by lilc-112** [torch/cunn#496]
~/Codes/torch/extra/cunn/lib/THCUNN/generic/SparseLinear.cu(95): error: identifier "cusparseScsrmm" is undefined

This func has been removed at CUDA11. and users of Ubuntu 20.04 have no choice for older versions

**Comment by hjk321** [comment]
Same issue. No fix?

**Comment by lilc-112** [comment]
I used to search for this func on the cuda docs. Maybe you can download the old versions cuda or Ubuntu. It seems I succeed on Ubuntu16. But half of a year passed, I couldn't remember the details, Sorry. 

If you have to compile torch(have no choice, the official recommands pytorch more), you can try old versions. Although it may take you lots of time.
