### ISSUE TITLE
SpatialMaxPooling failure case

### ISSUE THREAD

**Issue by soumith** [torch/cunn#53]
Fails for the case:
```lua
m=nn.SpatialMaxPooling(2,2,2,2):cuda()
input=torch.randn(128,1024,12,12):cuda()
m:forward(input)
```
```
error in SpatialMaxsampling.updateOutput: invalid argument
luajit: ...ch-distro/install/share/lua/5.1/nn/SpatialMaxPooling.lua:18: aborting
```

**Comment by jonathantompson** [comment]
Nice catch.

**Comment by soumith** [comment]
The reason here is that cunn is complied with 2.0 compability:

https://github.com/torch/cunn/blob/master/CMakeLists.txt#L19

If I switch that to 35, no problems

**Comment by russellfei** [comment]
@soumith Same catch here.

```
a = torch.rand(64,1024,12,12):cuda()
b = nn.SpatialMaxPooling(2,2,2,2):cuda():forward(a)
-- or -- 
b = nn.SpatialAdaptiveMaxPooling(8,8):cuda():forward(a)
```
gives the `invalid argument` error.
Maybe I should switch that arch to 35.
Thanks for instructions above.

**Comment by bamos** [comment]
Hi, I have the same issue with `SpatialAveragePooling` and changing the arch to 35 in `CMakeLists` fixes the problem.
