### ISSUE TITLE
cannot install cunn

### ISSUE THREAD

**Issue by kzachery** [torch/cunn#80]
Let me start by saying I am new to Torch7 and Lua. I have Torch7 installed under Ubuntu 14.04. I have successfully installed the nn package. Now, I and am trying to install the cunn package using:
luarocks install cunn

The following is the output of my install:
kzachery@DELL:~$ luarocks install cunn
Installing https://raw.githubusercontent.com/torch/rocks/master/cunn-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cunn-scm-1.rockspec... switching to 'build' mode
Cloning into 'cunn'...
remote: Counting objects: 47, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 47 (delta 18), reused 30 (delta 16), pack-reused 0
Receiving objects: 100% (47/47), 49.04 KiB | 0 bytes/s, done.
Resolving deltas: 100% (18/18), done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/kzachery/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/kzachery/torch/install/lib/luarocks/rocks/cunn/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/kzachery/torch/install
-- Found CUDA: /usr/local/cuda (found suitable version "7.0", minimum required is "4.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_cunn-scm-1-9119/cunn/build
[100%] Building NVCC (Device) object CMakeFiles/cunn.dir//./cunn_generated_init.cu.o
In file included from /tmp/luarocks_cunn-scm-1-9119/cunn/init.cu:14:0:
/tmp/luarocks_cunn-scm-1-9119/cunn/HardTanh.cu:2:24: fatal error: THCApply.cuh: No such file or directory
 #include "THCApply.cuh"
                        ^
compilation terminated.
CMake Error at cunn_generated_init.cu.o.cmake:206 (message):
  Error generating
  /tmp/luarocks_cunn-scm-1-9119/cunn/build/CMakeFiles/cunn.dir//./cunn_generated_init.cu.o

make[2]: *** [CMakeFiles/cunn.dir/./cunn_generated_init.cu.o] Error 1
make[1]: *** [CMakeFiles/cunn.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

What am I missing in order to get this package installed? Any help you could provide would be greatly appreciated.

**Comment by szagoruyko** [comment]
you have to update cutorch first, you have an outdated version

**Comment by kzachery** [comment]
Many thanks!

**Comment by wafflette** [comment]
For the record I had a somewhat similar issue. In my case i was getting this error after running torch:

/usr/local/bin/luajit: /usr/local/share/lua/5.1/trepl/init.lua:363: /usr/local/share/lua/5.1/trepl/init.lua:363: /usr/local/share/lua/5.1/luarocks/loader.l
ua:117: error loading module 'libcunn' from file '/usr/local/lib/lua/5.1/libcunn.so':                                                                      
        libcudart.so.5.5: cannot open shared object file: No such file or directory       

Also I'm on 14.10 and had to install IPython manually since there's no distribution package.

"sudo luarocks install cutorch"
"sudo luarocks install cunn"

**Comment by afgenovese** [comment]
How to update cutorch?

**Comment by taineleau** [comment]
@afgenovese luarocks install cutorch
