### ISSUE TITLE
VolumetricMaxPooling doesn't have cunn lib

### ISSUE THREAD

**Issue by lisabug** [torch/cunn#82]
With VolumetricConvolution have cunn lib, VolumetricMaxPooling doesn't have it.

**Comment by dominikgrewe** [comment]
Also, VolumetricAveragePooling is missing. Does anyone have an implementation of those two methods?

**Comment by kmul00** [comment]
@dominikgrewe Check [this]. (https://groups.google.com/forum/#!searchin/torch7/koustav/torch7/FFC1D_41CwQ/aMEefD6PSv0J)

The commit is yet not merged into the master.

**Comment by dominikgrewe** [comment]
Thanks. Forgot about that one!
