### ISSUE TITLE
cuda convolutional autoencoder (spatialConvolutionCUDA)

### ISSUE THREAD

**Issue by volkov68** [torch/cunn#9]
hi guys,
in the "koraykv/unsup" package there is a conv-psd autoencoder, i was trying to do something similar using cunn, but the spatialConvolutionCUDA module only allows output feature maps that are multiples of 16, so i wasn't able to make a decoder. does anybody know how to work around this?
thanks a lot

**Comment by ssakhavi** [comment]
@soumith, the `nn.SpatialConvolutionMap`  (used in CAE) also doesn't have a CUDA implementation. Therefore, it can't be sped up using GPU. 

Any alternatives?

**Comment by soumith** [comment]
SpatialFullConvolution should help for CAEs right...? now has cuda support.
