### ISSUE TITLE
Discrepency in output dimension while using VolumetricConvolution in CUDA from normal CPU version

### ISSUE THREAD

**Issue by kmul00** [torch/cunn#92]
Running `VolumetricConvolution` in CUDA mode seems to alternate the dimension of the output tensor.
For example, I have an input batch of 5D as follows:

    input = torch.Tensor(20, 2, 32, 64, 64)
I only have one layer as follows:

    model:add(nn.VolumetricConvolution(2, 16, 1, 5, 5))

In CPU mode, doing a forward pass produces the correct output of dimension `(20, 16, 32, 60, 60)`.
But in CUDA the dimensions get swapped and I get the output dimension as `(20, 16, 60, 32, 60)`, which shouldn't be the case.

Ideally, both should produce the same output.

**Comment by venu9** [comment]
Is this issue of VolumetricConvolution in CUDA fixed?

**Comment by soumith** [comment]
@venu9 hasn't been fixed yet, but in the meanwhile, feel free to use the bugfree cudnn.VolumetricConvolution
